# ui/launcher/card_data.py -- generated for the card recommender (cards/stamps step).
#
# Card code -> metadata, sourced from IdleonToolbox data/website-data.json
# (the "cards" map; 2026-06-16). perTier is the base copies-per-tier that
# drives the star thresholds (see card_recommender.calculate_stars, ported
# from IdleonToolbox parsers/cards.ts). effect/category are for display.
#
# Regenerate: re-run the generator in the commit that added this file.

CARD_META: dict[str, dict] = {
    'AlienTree': {"name": 'Alien Tree', "per_tier": 10, "effect": '+% Total Choppin Efficiency', "set": 'Medium Resources'},
    'Bandit_Bob': {"name": 'Bandit Bob', "per_tier": 1, "effect": '+% Money from Monsters', "set": 'Yum Yum Desert'},
    'BirchTree': {"name": 'Birch Tree', "per_tier": 10, "effect": '+% Total Choppin Efficiency', "set": 'Easy Resources'},
    'Boss2A': {"name": 'Efaunt', "per_tier": 1, "effect": '+% EXP from monsters', "set": 'Bosses'},
    'Boss2B': {"name": 'Chaotic Efaunt', "per_tier": 1, "effect": '+% Skill EXP', "set": 'Bosses'},
    'Boss2C': {"name": 'Gilded Efaunt', "per_tier": 11, "effect": '+ Star Talent Pts (Passive)', "set": 'Bosses'},
    'Boss3A': {"name": 'Chizoar', "per_tier": 1, "effect": '+% Cog Build Spd (Passive)', "set": 'Bosses'},
    'Boss3B': {"name": 'Chaotic Chizoar', "per_tier": 1, "effect": '+% Shrine Effects (Passive)', "set": 'Bosses'},
    'Boss3C': {"name": 'Blighted Chizoar', "per_tier": 12, "effect": '+% All Stat', "set": 'Bosses'},
    'Boss4A': {"name": 'Massive Troll', "per_tier": 2, "effect": '+% Kitchen Speed (Passive)', "set": 'Bosses'},
    'Boss4B': {"name": 'Chaotic Troll', "per_tier": 2, "effect": '+% All Skill Efficiency', "set": 'Bosses'},
    'Boss4C': {"name": 'Blitzkrieg Troll', "per_tier": 4, "effect": '+% Total Damage', "set": 'Bosses'},
    'Boss5A': {"name": 'Kattlekruk', "per_tier": 3, "effect": '+% Sailing Speed (Passive)', "set": 'Bosses'},
    'Boss5B': {"name": 'Chaotic Kattlekruk', "per_tier": 4, "effect": '+% EXP from monsters', "set": 'Bosses'},
    'Boss5C': {"name": 'Sacrilegious Kattlekruk', "per_tier": 5, "effect": '+% Money from Monsters', "set": 'Bosses'},
    'Boss6A': {"name": 'Emperor', "per_tier": 6, "effect": '+% Total Drop Rate', "set": 'Bosses'},
    'Boss6B': {"name": 'Chaotic Emperor', "per_tier": 9, "effect": '+% Total Damage Multi', "set": 'Bosses'},
    'Boss6C': {"name": 'Sovereign Emperor', "per_tier": 13, "effect": '+% Multikill per tier', "set": 'Bosses'},
    'Bug1': {"name": 'Flies', "per_tier": 10, "effect": '+% Monster EXP While Active', "set": 'Easy Resources'},
    'Bug10': {"name": 'Dust Mote', "per_tier": 15, "effect": '+% Catching Away Gains', "set": 'Hard Resources'},
    'Bug12': {"name": 'Ladybug', "per_tier": 15, "effect": '+% Total Catching Efficiency', "set": 'Hard Resources'},
    'Bug13': {"name": 'Firefly', "per_tier": 15, "effect": '+% Catching Speed', "set": 'Hard Resources'},
    'Bug14': {"name": 'Fractalfly', "per_tier": 1000, "effect": '+% Total Catching Efficiency', "set": 'Hard Resources'},
    'Bug2': {"name": 'Butterflies', "per_tier": 10, "effect": '+% Total Catching Efficiency', "set": 'Easy Resources'},
    'Bug3': {"name": 'Sentient Cereal', "per_tier": 10, "effect": '+% Catching EXP', "set": 'Medium Resources'},
    'Bug4': {"name": 'Fruitflies', "per_tier": 10, "effect": '+% Catching Away Gains', "set": 'Medium Resources'},
    'Bug5': {"name": 'Mosquisnow', "per_tier": 10, "effect": '+% Total Catching Efficiency', "set": 'Medium Resources'},
    'Bug6': {"name": 'Flycicle', "per_tier": 10, "effect": '+% Catching Away Gains', "set": 'Medium Resources'},
    'Bug7': {"name": 'Bumble Bee', "per_tier": 10, "effect": '+% Total Catching Efficiency', "set": 'Medium Resources'},
    'Bug8': {"name": 'Fairy', "per_tier": 10, "effect": '+% Catching Speed', "set": 'Hard Resources'},
    'Bug9': {"name": 'Scarab', "per_tier": 12, "effect": '+% Total Catching Efficiency', "set": 'Hard Resources'},
    'Copper': {"name": 'Copper', "per_tier": 10, "effect": '+ Base accuracy', "set": 'Easy Resources'},
    'CritterCard1': {"name": 'Froge', "per_tier": 4, "effect": '+% Shiny Critter Chance', "set": 'Medium Resources'},
    'CritterCard10': {"name": 'Blobfish', "per_tier": 12, "effect": '+% Shiny Critter Chance', "set": 'Hard Resources'},
    'CritterCard11': {"name": 'Tuttle', "per_tier": 50, "effect": '+% Shiny Critter Chance', "set": 'Hard Resources'},
    'CritterCard2': {"name": 'Crabbo', "per_tier": 4, "effect": '+% Trapping Efficiency', "set": 'Medium Resources'},
    'CritterCard3': {"name": 'Scorpie', "per_tier": 4, "effect": '+% Trapping EXP', "set": 'Medium Resources'},
    'CritterCard4': {"name": 'Mousey', "per_tier": 4, "effect": '+% Shiny Critter Chance', "set": 'Medium Resources'},
    'CritterCard5': {"name": 'Owlio', "per_tier": 4, "effect": '+% EXP from monsters', "set": 'Medium Resources'},
    'CritterCard6': {"name": 'Pingy', "per_tier": 5, "effect": '+% Shiny Critter Chance', "set": 'Hard Resources'},
    'CritterCard7': {"name": 'Bunny', "per_tier": 6, "effect": '+% Skill AFK gain rate', "set": 'Hard Resources'},
    'CritterCard8': {"name": 'Dung Beat', "per_tier": 7, "effect": '+% Trapping Efficiency', "set": 'Hard Resources'},
    'CritterCard9': {"name": 'Honker', "per_tier": 9, "effect": '+% Trapping EXP', "set": 'Hard Resources'},
    'Crystal0': {"name": 'Crystal Carrot', "per_tier": 3, "effect": '+% Total Drop Rate', "set": 'Blunder Hills'},
    'Crystal1': {"name": 'Crystal Crabal', "per_tier": 3, "effect": '+% EXP from monsters', "set": 'Yum Yum Desert'},
    'Crystal2': {"name": 'Crystal Cattle', "per_tier": 10, "effect": '+% EXP from monsters', "set": 'Frostbite Tundra'},
    'Crystal3': {"name": 'Crystal Custard', "per_tier": 10, "effect": '+px Line Width (Passive)', "set": 'Hyperion Nebula'},
    'Crystal4': {"name": 'Crystal Capybara', "per_tier": 15, "effect": '+% Skill Efficncy (Passive)', "set": "Smolderin' Plateau"},
    'Crystal5': {"name": 'Crystal Candalight', "per_tier": 5000, "effect": '+% Sneaking Stealth (Passive)', "set": 'Spirited Valley'},
    'Crystal6': {"name": 'Crystal Cuttlefish', "per_tier": 2500000, "effect": '+% Damage Multi (Passive)', "set": 'Shimmerfin Deep'},
    'Dementia': {"name": 'Dementia', "per_tier": 10, "effect": '+% Mining Speed', "set": 'Medium Resources'},
    'Dreadlo': {"name": 'Dreadlo', "per_tier": 15, "effect": '+% Mining Away Gains', "set": 'Hard Resources'},
    'EasterEvent1': {"name": 'Egggulyte', "per_tier": 1, "effect": '+% Card Drop Chance', "set": 'Events'},
    'EasterEvent2': {"name": 'Egg Capsule', "per_tier": 1, "effect": '+% Critical Damage', "set": 'Events'},
    'Fish1': {"name": 'Goldfish', "per_tier": 10, "effect": '+% Total MP', "set": 'Easy Resources'},
    'Fish10': {"name": 'Shellfish', "per_tier": 18, "effect": '+% Total Fishing Efficiency', "set": 'Hard Resources'},
    'Fish11': {"name": 'Jumbo Shrimp', "per_tier": 24, "effect": '+% Fishing Away Gains', "set": 'Hard Resources'},
    'Fish12': {"name": 'Caulifish', "per_tier": 30, "effect": '+% Fishing Speed', "set": 'Hard Resources'},
    'Fish2': {"name": 'Hermit Can', "per_tier": 10, "effect": '+% Total Fishing Efficiency', "set": 'Easy Resources'},
    'Fish3': {"name": 'Jellyfish', "per_tier": 10, "effect": '+% Fishing EXP', "set": 'Easy Resources'},
    'Fish4': {"name": 'Bloach', "per_tier": 10, "effect": '+% Fishing Away Gains', "set": 'Medium Resources'},
    'Fish5': {"name": 'Skelefish', "per_tier": 8, "effect": '+% Total Fishing Efficiency', "set": 'Medium Resources'},
    'Fish6': {"name": 'Shark', "per_tier": 10, "effect": '+% Fishing Speed', "set": 'Medium Resources'},
    'Fish7': {"name": 'Manta Ray', "per_tier": 10, "effect": '+% Fishing EXP', "set": 'Medium Resources'},
    'Fish8': {"name": 'Kraken', "per_tier": 10, "effect": '+% Fishing Away Gains', "set": 'Medium Resources'},
    'Fish9': {"name": 'Icefish', "per_tier": 15, "effect": '+% Fishing EXP', "set": 'Hard Resources'},
    'ForestTree': {"name": 'Forest Tree', "per_tier": 10, "effect": '+% EXP Conversion from Talent', "set": 'Easy Resources'},
    'ForgeA': {"name": 'Fire Forge', "per_tier": 10, "effect": '+% Smithing EXP (Passive)', "set": 'Easy Resources'},
    'ForgeB': {"name": 'Cinder Forge', "per_tier": 10, "effect": '+% Smithing EXP (Passive)', "set": 'Medium Resources'},
    'Godshard': {"name": 'Godshard', "per_tier": 400, "effect": '+% Forge Cap and SPD (Passive)', "set": 'Hard Resources'},
    'Gold': {"name": 'Gold', "per_tier": 10, "effect": '+% Mining EXP', "set": 'Easy Resources'},
    'Iron': {"name": 'Iron', "per_tier": 10, "effect": '+% Total Mining Efficiency', "set": 'Easy Resources'},
    'JungleTree': {"name": 'Jungle Tree', "per_tier": 10, "effect": '+% Choppin EXP', "set": 'Easy Resources'},
    'Lustre': {"name": 'Lustre', "per_tier": 10, "effect": '+% Mining Speed', "set": 'Medium Resources'},
    'OakTree': {"name": 'Oak Tree', "per_tier": 10, "effect": '+ Base Defence', "set": 'Easy Resources'},
    'PalmTree': {"name": 'Palm Tree', "per_tier": 10, "effect": '+% Choppin Away Gains', "set": 'Medium Resources'},
    'Plat': {"name": 'Plat', "per_tier": 10, "effect": '+% Mining Away Gains', "set": 'Medium Resources'},
    'Prehistrium': {"name": 'Prehistrium', "per_tier": 5000, "effect": '+% Mining Away Gains', "set": 'Hard Resources'},
    'SaharanFoal': {"name": 'Saharan Foal', "per_tier": 10, "effect": '+% Choppin Away Gains', "set": 'Medium Resources'},
    'SoulCard1': {"name": 'Forest Soul', "per_tier": 3, "effect": '+% Defence from Equipment', "set": 'Medium Resources'},
    'SoulCard2': {"name": 'Dune Soul', "per_tier": 3, "effect": '+ Starting Pts in Worship', "set": 'Medium Resources'},
    'SoulCard3': {"name": 'Rooted Soul', "per_tier": 3, "effect": '+ Starting Pts in Worship', "set": 'Medium Resources'},
    'SoulCard4': {"name": 'Frigid Soul', "per_tier": 4, "effect": '+% Max Charge', "set": 'Medium Resources'},
    'SoulCard5': {"name": 'Squishy Soul', "per_tier": 5, "effect": '+% Charge Rate', "set": 'Hard Resources'},
    'SoulCard6': {"name": 'Oozie Soul', "per_tier": 7, "effect": '+% Max Charge', "set": 'Hard Resources'},
    'SoulCard7': {"name": 'Breezy Soul', "per_tier": 7, "effect": '+% Charge Rate', "set": 'Hard Resources'},
    'SoulCard8': {"name": 'Deepsea Soul', "per_tier": 250, "effect": '+ Starting Pts in Worship', "set": 'Hard Resources'},
    'SpelunkingCard0': {"name": 'Fearful Tunnel', "per_tier": 100, "effect": '+% Spelunking EXP', "set": 'Hard Resources'},
    'SpelunkingCard1': {"name": 'Decaying Crevasse', "per_tier": 300, "effect": '+% Spelunking Efficiency', "set": 'Hard Resources'},
    'SpelunkingCard2': {"name": 'Buried Church', "per_tier": 3000, "effect": '+% Spelunking AFK Gain', "set": 'Hard Resources'},
    'SpelunkingCard3': {"name": 'One Way Opening', "per_tier": 40000, "effect": '+% Spelunking EXP', "set": 'Hard Resources'},
    'SpelunkingCard4': {"name": 'Plunder Cranny', "per_tier": 150000, "effect": '+% Spelunking AFK Gain', "set": 'Hard Resources'},
    'SpelunkingCard5': {"name": 'Kelp Forest', "per_tier": 2500000, "effect": '+% Spelunking EXP', "set": 'Hard Resources'},
    'Starfire': {"name": 'Starfire', "per_tier": 12, "effect": '+% Mining EXP', "set": 'Hard Resources'},
    'StumpTree': {"name": 'Stump Tree', "per_tier": 10, "effect": '+% Total Accuracy', "set": 'Medium Resources'},
    'SummerEvent1': {"name": 'Coastiolyte', "per_tier": 8, "effect": '+% Fishing Away Gains', "set": 'Events'},
    'SummerEvent2': {"name": 'Summer Spirit', "per_tier": 8, "effect": '+% Catching EXP', "set": 'Events'},
    'ToiletTree': {"name": 'Toilet Tree', "per_tier": 10, "effect": '+% Choppin Speed', "set": 'Medium Resources'},
    'Tree10': {"name": 'Dandelioli Tree', "per_tier": 15, "effect": '+% Choppin Speed', "set": 'Hard Resources'},
    'Tree12': {"name": 'Bamboo', "per_tier": 15, "effect": '+% Total Choppin Efficiency', "set": 'Hard Resources'},
    'Tree13': {"name": 'Effervescent Eucalyptus', "per_tier": 15, "effect": '+% Choppin Away Gains', "set": 'Hard Resources'},
    'Tree14': {"name": 'Ancient Seaweed', "per_tier": 1000, "effect": '+% Choppin Away Gains', "set": 'Hard Resources'},
    'Tree7': {"name": 'Wispy Tree', "per_tier": 10, "effect": '+% Choppin Speed', "set": 'Medium Resources'},
    'Tree8': {"name": 'Cubed Tree', "per_tier": 10, "effect": '+% Choppin Speed', "set": 'Medium Resources'},
    'Tree9': {"name": 'Maple Tree', "per_tier": 12, "effect": '+% Choppin Away Gains', "set": 'Hard Resources'},
    'Void': {"name": 'Void', "per_tier": 10, "effect": '+% Total Mining Efficiency', "set": 'Medium Resources'},
    'acorn': {"name": 'Nutto', "per_tier": 10, "effect": '+% Money from Monsters', "set": 'Blunder Hills'},
    'anni4Event1': {"name": 'IdleOn 4th Anniversary', "per_tier": 4, "effect": '+% Drop Rate (Passive)', "set": 'Events'},
    'anni5Event1': {"name": 'IdleOn 5th Anniversary', "per_tier": 6, "effect": '+% Gold Food Effect (Passive)', "set": 'Events'},
    'babaHour': {"name": 'Biggie Hours', "per_tier": 1, "effect": '+% Double AFK claim chance', "set": 'Bosses'},
    'babaMummy': {"name": 'King Doot', "per_tier": 1, "effect": '+% Total Drop Rate', "set": 'Bosses'},
    'babayaga': {"name": 'Baba Yaga', "per_tier": 1, "effect": '+% Money from Monsters', "set": 'Bosses'},
    'beanG': {"name": 'Bored Bean', "per_tier": 7, "effect": '+ Base Damage', "set": 'Blunder Hills'},
    'bloque': {"name": 'Bloque', "per_tier": 14, "effect": '+ Base AGI', "set": 'Frostbite Tundra'},
    'branch': {"name": 'Walking Stick', "per_tier": 10, "effect": '+ Base WIS', "set": 'Blunder Hills'},
    'cactus': {"name": 'Cactopunk', "per_tier": 2, "effect": '+% Dungeon Boss Dmg', "set": 'Dungeons'},
    'carrotO': {"name": 'Carrotman', "per_tier": 10, "effect": '+ Base AGI', "set": 'Blunder Hills'},
    'caveB': {"name": 'Gloomie Mushroom', "per_tier": 5000, "effect": '+% Villager EXP (Passive)', "set": "Smolderin' Plateau"},
    'caveC': {"name": 'Ancient Golem', "per_tier": 10000, "effect": '+% Total Drop Rate (Passive)', "set": "Smolderin' Plateau"},
    'coconut': {"name": 'Mafioso', "per_tier": 10, "effect": '+ Base AGI', "set": 'Yum Yum Desert'},
    'crabcake': {"name": 'Crabcake', "per_tier": 10, "effect": '+% To not consume Food', "set": 'Yum Yum Desert'},
    'crabcakeB': {"name": 'Mr Blueberry', "per_tier": 4, "effect": '+% Total Drop Rate', "set": 'Events'},
    'cropfallEvent1': {"name": 'Bort The Cornhusk', "per_tier": 6, "effect": '+% Gold Food Effect (Passive)', "set": 'Events'},
    'demonP': {"name": 'Demon Genie', "per_tier": 19, "effect": '+% Crystal Mob Spawn Chance', "set": 'Hyperion Nebula'},
    'eye': {"name": 'Neyeptune', "per_tier": 17, "effect": '+% Total Accuracy', "set": 'Frostbite Tundra'},
    'fallEvent1': {"name": 'Falloween Pumpkin', "per_tier": 3, "effect": '+ Star Talent Pts (Passive)', "set": 'Events'},
    'flake': {"name": 'Frost Flake', "per_tier": 12, "effect": '+ Base STR', "set": 'Frostbite Tundra'},
    'frogBIG': {"name": 'Gigafrog', "per_tier": 10, "effect": '+% Card Drop Chance', "set": 'Blunder Hills'},
    'frogD': {"name": 'Globohopper', "per_tier": 2, "effect": '+% Block Chance', "set": 'Dungeons'},
    'frogG': {"name": 'Frog', "per_tier": 6, "effect": '+ Base MP', "set": 'Blunder Hills'},
    'frogGG': {"name": 'Eldritch Croaker', "per_tier": 5, "effect": '% to start with RNG orb (Passive)', "set": 'Dungeons'},
    'frogGR': {"name": 'Grandfrogger', "per_tier": 1, "effect": '% to start with RNG orb (Passive)', "set": 'Dungeons'},
    'frogGR2': {"name": 'Rotting Grandfrogger', "per_tier": 1, "effect": '+% Dungeon Flurbos', "set": 'Dungeons'},
    'frogGR3': {"name": 'Forlorn Grandfrogger', "per_tier": 1, "effect": '+% Dungeon Credits', "set": 'Dungeons'},
    'frogGR4': {"name": 'Vengeful Grandfrogger', "per_tier": 1, "effect": '+% Dungeon Move Speed', "set": 'Dungeons'},
    'frogP': {"name": 'Poisonic Frog', "per_tier": 1, "effect": '+ Base Dungeon MP', "set": 'Dungeons'},
    'frogR': {"name": 'Lava Slimer', "per_tier": 2, "effect": '+% Dungeon Card Chance', "set": 'Dungeons'},
    'frogW': {"name": 'Chromatium Frog', "per_tier": 3, "effect": '+% Dungeon Credits', "set": 'Dungeons'},
    'frogY': {"name": 'King Frog', "per_tier": 2, "effect": '+ Base Dungeon Damage', "set": 'Dungeons'},
    'ghost': {"name": 'Ghost', "per_tier": 2, "effect": '+% Monster EXP While Active', "set": 'Events'},
    'glass': {"name": 'Quenchie', "per_tier": 17, "effect": '+ Base LUK', "set": 'Frostbite Tundra'},
    'goblinG': {"name": 'Glublin', "per_tier": 10, "effect": '+% Total HP', "set": 'Blunder Hills'},
    'iceBossZ': {"name": 'Glaciaxus', "per_tier": 2, "effect": '+% Dungeon Card Chance', "set": 'Dungeons'},
    'iceBossZ2': {"name": 'Golden Glaciaxus', "per_tier": 1, "effect": '+% Dungeon Credits', "set": 'Dungeons'},
    'iceBossZ3': {"name": 'Caustic Glaciaxus', "per_tier": 1, "effect": '+% Total Dungeon Dmg', "set": 'Dungeons'},
    'iceknight': {"name": 'Ice Guard', "per_tier": 8, "effect": '+% Dungeon MP regen', "set": 'Dungeons'},
    'jarSand': {"name": 'Sandy Pot', "per_tier": 10, "effect": '+% EXP Conversion from Talent', "set": 'Yum Yum Desert'},
    'loveEvent': {"name": 'Loveulyte', "per_tier": 1, "effect": '+% Total HP', "set": 'Events'},
    'loveEvent2': {"name": 'Chocco Box', "per_tier": 1, "effect": '+% Boost Food Effect', "set": 'Events'},
    'loveEvent3': {"name": 'Giant Rose', "per_tier": 1, "effect": '+% EXP from monsters', "set": 'Events'},
    'luckEvent1': {"name": 'Luckulyte', "per_tier": 5, "effect": '+% Drop Rate (Passive)', "set": 'Events'},
    'luckEvent2': {"name": 'Potluck', "per_tier": 5, "effect": '+% Money from Monsters', "set": 'Events'},
    'mamoth': {"name": 'Mamooth', "per_tier": 15, "effect": '+% Total HP', "set": 'Frostbite Tundra'},
    'mimicA': {"name": 'Mimic', "per_tier": 10, "effect": '+% Total Drop Rate', "set": 'Yum Yum Desert'},
    'mini3a': {"name": 'Dilapidated Slush', "per_tier": 5, "effect": '+% Money from Monsters', "set": 'Bosses'},
    'mini4a': {"name": 'Mutated Mush', "per_tier": 5, "effect": '+% Cooking EXP gain', "set": 'Bosses'},
    'mini5a': {"name": 'Domeo Magmus', "per_tier": 4, "effect": '+% Total Drop Rate (Passive)', "set": 'Bosses'},
    'mini6a': {"name": 'Demented Spiritlord', "per_tier": 5, "effect": '+% Fighting AFK gain rate', "set": 'Bosses'},
    'moonman': {"name": 'Moonmoon', "per_tier": 10, "effect": '+% Monster EXP While Active', "set": 'Yum Yum Desert'},
    'mushG': {"name": 'Green Mushroom', "per_tier": 5, "effect": '+ Base HP', "set": 'Blunder Hills'},
    'mushP': {"name": 'Purp Mushroom', "per_tier": 15, "effect": '+% Money from Monsters', "set": 'Hyperion Nebula'},
    'mushR': {"name": 'Red Mushroom', "per_tier": 10, "effect": '+ Base LUK', "set": 'Blunder Hills'},
    'mushW': {"name": 'Wood Mushroom', "per_tier": 10, "effect": '+% Total Accuracy', "set": 'Blunder Hills'},
    'penguin': {"name": 'Penguin', "per_tier": 15, "effect": '+ Base WIS', "set": 'Frostbite Tundra'},
    'pincermin': {"name": 'Pincermin', "per_tier": 10, "effect": '+ Weapon Power', "set": 'Yum Yum Desert'},
    'plank': {"name": 'Wode Board', "per_tier": 10, "effect": '+ Base STR', "set": 'Blunder Hills'},
    'poopBig': {"name": 'Dr Defecaus', "per_tier": 1, "effect": '+% Total Damage', "set": 'Bosses'},
    'poopD': {"name": 'Boop', "per_tier": 1, "effect": '+% Fighting AFK gain rate', "set": 'Bosses'},
    'poopSmall': {"name": 'Poop', "per_tier": 10, "effect": '+% Crystal Mob Spawn Chance', "set": 'Blunder Hills'},
    'potato': {"name": 'Mashed Potato', "per_tier": 10, "effect": '+% Critical Damage', "set": 'Yum Yum Desert'},
    'potatoB': {"name": 'Crescent Spud', "per_tier": 5, "effect": '+% Dungeon MP regen', "set": 'Dungeons'},
    'ram': {"name": 'Dedotated Ram', "per_tier": 20, "effect": '+ Weapon Power', "set": 'Frostbite Tundra'},
    'ratB': {"name": 'Rat', "per_tier": 10, "effect": '+% Critical Chance', "set": 'Blunder Hills'},
    'rocky': {"name": 'Grumblo', "per_tier": 2, "effect": '+% Dungeon Card Chance', "set": 'Dungeons'},
    'sandcastle': {"name": 'Sand Castle', "per_tier": 10, "effect": '+% Total Accuracy', "set": 'Yum Yum Desert'},
    'sandgiant': {"name": 'Sand Giant', "per_tier": 10, "effect": '+% Minimum Damage', "set": 'Yum Yum Desert'},
    'sheep': {"name": 'Sheepie', "per_tier": 11, "effect": '+% Defence from Equipment', "set": 'Frostbite Tundra'},
    'sheepB': {"name": 'Floofie', "per_tier": 3, "effect": '+% MP regen rate', "set": 'Events'},
    'shovelR': {"name": 'Dig Doug', "per_tier": 10, "effect": '+ Base LUK', "set": 'Yum Yum Desert'},
    'shovelY': {"name": 'Plasti Doug', "per_tier": 4, "effect": '+ Base Defence', "set": 'Events'},
    'skele': {"name": 'Xylobone', "per_tier": 15, "effect": '+% Critical Chance', "set": 'Frostbite Tundra'},
    'skele2': {"name": 'Bloodbone', "per_tier": 15, "effect": '+% Total Damage', "set": 'Frostbite Tundra'},
    'slimeB': {"name": 'Glunko The Massive', "per_tier": 2, "effect": '+ Weapon Power', "set": 'Bosses'},
    'slimeG': {"name": 'Slime', "per_tier": 8, "effect": '+ Base WIS', "set": 'Blunder Hills'},
    'slimeR': {"name": 'Valenslime', "per_tier": 2, "effect": '+% Defence from Equipment', "set": 'Events'},
    'snailZ': {"name": 'Snelbie', "per_tier": 10, "effect": '+% Card Drop Chance', "set": 'Yum Yum Desert'},
    'snakeB': {"name": 'Cryosnake', "per_tier": 17, "effect": '+% MP regen rate', "set": 'Frostbite Tundra'},
    'snakeG': {"name": 'Baby Boa', "per_tier": 9, "effect": '+ Move Spd', "set": 'Blunder Hills'},
    'snakeY': {"name": 'Shell Snake', "per_tier": 3, "effect": '+ Base LUK', "set": 'Events'},
    'snakeZ': {"name": 'Snakenhotep', "per_tier": 1, "effect": '+% Dungeon Drop Rate', "set": 'Dungeons'},
    'snakeZ2': {"name": 'Enraged Snakenhotep', "per_tier": 1, "effect": '+% Total Dungeon Dmg', "set": 'Dungeons'},
    'snakeZ3': {"name": 'Inevitable Snakenhotep', "per_tier": 1, "effect": '+% Dungeon Flurbos', "set": 'Dungeons'},
    'snowball': {"name": 'Snowman', "per_tier": 15, "effect": '+% Total Damage', "set": 'Frostbite Tundra'},
    'speaker': {"name": 'Bop Box', "per_tier": 17, "effect": '+% Total Drop Rate', "set": 'Frostbite Tundra'},
    'springEvent1': {"name": 'Bubbulyte', "per_tier": 1, "effect": '+% Class EXP (Passive)', "set": 'Events'},
    'springEvent2': {"name": 'Spring Splendor', "per_tier": 1, "effect": '+% All Skill EXP (Passive)', "set": 'Events'},
    'stache': {"name": 'Sir Stache', "per_tier": 13, "effect": '+% Card Drop Chance', "set": 'Frostbite Tundra'},
    'steak': {"name": 'Tyson', "per_tier": 10, "effect": '+ Base STR', "set": 'Yum Yum Desert'},
    'steakR': {"name": 'Beefie', "per_tier": 2, "effect": '+% Dungeon Money', "set": 'Dungeons'},
    'target': {"name": 'Target', "per_tier": 2, "effect": '+ Base Dungeon HP', "set": 'Dungeons'},
    'thermostat': {"name": 'Thermister', "per_tier": 15, "effect": '+% Critical Damage', "set": 'Frostbite Tundra'},
    'totem': {"name": 'Lazlo', "per_tier": 2, "effect": '+% RNG item rarity', "set": 'Dungeons'},
    'w4a2': {"name": 'TV', "per_tier": 17, "effect": '+% Breeding EXP (Passive)', "set": 'Hyperion Nebula'},
    'w4a3': {"name": 'Donut', "per_tier": 18, "effect": '+% Defence from Equipment', "set": 'Hyperion Nebula'},
    'w4b1': {"name": 'Flying Worm', "per_tier": 21, "effect": '+ Base WIS', "set": 'Hyperion Nebula'},
    'w4b2': {"name": 'Soda Can', "per_tier": 20, "effect": '+ Star Talent Pts (Passive)', "set": 'Hyperion Nebula'},
    'w4b3': {"name": 'Gelatinous Cuboid', "per_tier": 22, "effect": '+% Lab EXP gain', "set": 'Hyperion Nebula'},
    'w4b4': {"name": 'Choccie', "per_tier": 23, "effect": '+ Weapon Power', "set": 'Hyperion Nebula'},
    'w4b5': {"name": 'Biggole Wurm', "per_tier": 24, "effect": '+ Base AGI', "set": 'Hyperion Nebula'},
    'w4c1': {"name": 'Clammie', "per_tier": 26, "effect": '+% Multikill per tier', "set": 'Hyperion Nebula'},
    'w4c2': {"name": 'Octodar', "per_tier": 27, "effect": '+ Base STR', "set": 'Hyperion Nebula'},
    'w4c3': {"name": 'Flombeige', "per_tier": 28, "effect": '+% Critical Chance (Passive)', "set": 'Hyperion Nebula'},
    'w4c4': {"name": 'Stilted Seeker', "per_tier": 30, "effect": '+% All Stat', "set": 'Hyperion Nebula'},
    'w5a1': {"name": 'Suggma', "per_tier": 25, "effect": '+% Multikill per tier', "set": "Smolderin' Plateau"},
    'w5a2': {"name": 'Maccie', "per_tier": 28, "effect": '+% Defence from Equipment', "set": "Smolderin' Plateau"},
    'w5a3': {"name": 'Mister Brightside', "per_tier": 32, "effect": '+% Total Drop Rate', "set": "Smolderin' Plateau"},
    'w5a4': {"name": 'Cheese Nub', "per_tier": 35, "effect": '+% Skill EXP (Passive)', "set": "Smolderin' Plateau"},
    'w5a5': {"name": 'Stiltmole', "per_tier": 45, "effect": '+% Divinity EXP (Passive)', "set": "Smolderin' Plateau"},
    'w5b1': {"name": 'Molti', "per_tier": 48, "effect": '+% Money from mobs (Passive)', "set": "Smolderin' Plateau"},
    'w5b2': {"name": 'Purgatory Stalker', "per_tier": 52, "effect": '+ Weapon Power (Passive)', "set": "Smolderin' Plateau"},
    'w5b3': {"name": 'Citringe', "per_tier": 60, "effect": '+% Total Damage', "set": "Smolderin' Plateau"},
    'w5b4': {"name": 'Lampar', "per_tier": 65, "effect": '+% EXP from monsters', "set": "Smolderin' Plateau"},
    'w5b5': {"name": 'Fire Spirit', "per_tier": 70, "effect": '+ Base LUK', "set": "Smolderin' Plateau"},
    'w5b6': {"name": 'Biggole Mole', "per_tier": 75, "effect": '+% Mining Speed', "set": "Smolderin' Plateau"},
    'w5c1': {"name": 'Crawler', "per_tier": 80, "effect": '+% Sailing Speed (Passive)', "set": "Smolderin' Plateau"},
    'w5c2': {"name": 'Tremor Wurm', "per_tier": 100, "effect": '+% All Stat', "set": "Smolderin' Plateau"},
    'w6a1': {"name": 'Sprout Spirit', "per_tier": 50, "effect": '+% Total Damage', "set": 'Spirited Valley'},
    'w6a2': {"name": 'Ricecake', "per_tier": 60, "effect": '+% DEF from Equips (Passive)', "set": 'Spirited Valley'},
    'w6a3': {"name": 'River Spirit', "per_tier": 75, "effect": '+% All Stat', "set": 'Spirited Valley'},
    'w6a4': {"name": 'Baby Troll', "per_tier": 85, "effect": '+% Sneaking EXP (Passive)', "set": 'Spirited Valley'},
    'w6a5': {"name": 'Woodlin Spirit', "per_tier": 100, "effect": '+% Multikill per tier', "set": 'Spirited Valley'},
    'w6b1': {"name": 'Bamboo Spirit', "per_tier": 150, "effect": '+% Summoning EXP (Passive)', "set": 'Spirited Valley'},
    'w6b2': {"name": 'Lantern Spirit', "per_tier": 170, "effect": '+% Farming EXP (Passive)', "set": 'Spirited Valley'},
    'w6b3': {"name": 'Mama Troll', "per_tier": 200, "effect": '+% Skill AFK gain rate', "set": 'Spirited Valley'},
    'w6b4': {"name": 'Leek Spirit', "per_tier": 250, "effect": '+% Jade Coin gain (Passive)', "set": 'Spirited Valley'},
    'w6c1': {"name": 'Ceramic Spirit', "per_tier": 400, "effect": '+% Cooking Spd Multi (Passive)', "set": 'Spirited Valley'},
    'w6c2': {"name": 'Skydoggie Spirit', "per_tier": 500, "effect": '+ Base LUK', "set": 'Spirited Valley'},
    'w6d1': {"name": 'Royal Egg', "per_tier": 900, "effect": '+% Fighting AFK (Passive)', "set": 'Spirited Valley'},
    'w6d2': {"name": 'Minichief Spirit', "per_tier": 1300, "effect": '+% Total Drop Rate', "set": 'Spirited Valley'},
    'w6d3': {"name": 'Samurai Guardian', "per_tier": 2500, "effect": '+% All AFK Gains(Passive)', "set": 'Spirited Valley'},
    'w7a1': {"name": 'Equinox Broadbass', "per_tier": 5000, "effect": '+% Spelunking Efficiency', "set": 'Shimmerfin Deep'},
    'w7a10': {"name": 'Spearfish', "per_tier": 150000, "effect": '+% Stamina Regen (Passive)', "set": 'Shimmerfin Deep'},
    'w7a11': {"name": 'Coralcave Crab', "per_tier": 250000, "effect": '+% Gallery Bonus (Passive)', "set": 'Shimmerfin Deep'},
    'w7a12': {"name": 'Coralcave Guardian', "per_tier": 400000, "effect": '+% Drop Rate Multi', "set": 'Shimmerfin Deep'},
    'w7a2': {"name": 'Doodlefish', "per_tier": 7000, "effect": '+% Total Damage Multi', "set": 'Shimmerfin Deep'},
    'w7a3': {"name": 'Eamsy Earl', "per_tier": 8500, "effect": '+% Class EXP Multi', "set": 'Shimmerfin Deep'},
    'w7a4': {"name": 'Shellslug', "per_tier": 11000, "effect": '+% Spelunking AFK Gain', "set": 'Shimmerfin Deep'},
    'w7a5': {"name": 'Balloonfish', "per_tier": 15000, "effect": '+% Spelunk POW (Passive)', "set": 'Shimmerfin Deep'},
    'w7a6': {"name": 'Noble Clam', "per_tier": 25000, "effect": '+% Spelunking EXP', "set": 'Shimmerfin Deep'},
    'w7a7': {"name": 'Litterfish', "per_tier": 35000, "effect": '+% Spelunk Amber (Passive)', "set": 'Shimmerfin Deep'},
    'w7a8': {"name": 'Pufferblob', "per_tier": 65000, "effect": '+% Class EXP Multi', "set": 'Shimmerfin Deep'},
    'w7a9': {"name": 'Demonblub', "per_tier": 100000, "effect": '+% Daily Coral (Passive)', "set": 'Shimmerfin Deep'},
    'w7b1': {"name": 'Trench Fish', "per_tier": 100000, "effect": '+% Research EXP (Passive)', "set": 'Shimmerfin Deep'},
    'w7b10': {"name": 'Magni Pufferfin', "per_tier": 30000000, "effect": '+% Drop Rate Multi', "set": 'Shimmerfin Deep'},
    'w7b11': {"name": 'Pirate Deckhand', "per_tier": 20000000, "effect": '+% Research AFK gain (Passive)', "set": 'Shimmerfin Deep'},
    'w7b12': {"name": 'Dreadnaught Captain', "per_tier": 40000000, "effect": '+% Spelunk Amber (Passive)', "set": 'Shimmerfin Deep'},
    'w7b2': {"name": 'Boomy Mine', "per_tier": 300000, "effect": '+% Gaming Bit Multi (Passive)', "set": 'Shimmerfin Deep'},
    'w7b3': {"name": 'Pirate Underling', "per_tier": 500000, "effect": '+% Flaggy Rate Multi (Passive)', "set": 'Shimmerfin Deep'},
    'w7b4': {"name": 'Eggroll', "per_tier": 900000, "effect": '+% Research EXP (Passive)', "set": 'Shimmerfin Deep'},
    'w7b5': {"name": 'Jellofish', "per_tier": 1500000, "effect": '+% Farming EVO Multi (Passive)', "set": 'Shimmerfin Deep'},
    'w7b6': {"name": 'Kelpfish', "per_tier": 3500000, "effect": '+% Class EXP Multi', "set": 'Shimmerfin Deep'},
    'w7b7': {"name": 'Mantaray', "per_tier": 6000000, "effect": '+% Drop Rate Multi', "set": 'Shimmerfin Deep'},
    'w7b8': {"name": 'Glowfish', "per_tier": 10000000, "effect": '+% Research EXP (Passive)', "set": 'Shimmerfin Deep'},
    'w7b9': {"name": 'Ancientfish', "per_tier": 20000000, "effect": '+% Drop Rate Multi', "set": 'Shimmerfin Deep'},
    'wolfA': {"name": 'Amarok', "per_tier": 1, "effect": '+% Skill AFK gain rate', "set": 'Bosses'},
    'wolfB': {"name": 'Chaotic Amarok', "per_tier": 1, "effect": '+% Fighting AFK gain rate', "set": 'Bosses'},
    'wolfC': {"name": 'Radiant Amarok', "per_tier": 10, "effect": '+ Weapon Power', "set": 'Bosses'},
    'xmasEvent': {"name": 'Giftmas Blobulyte', "per_tier": 1, "effect": '+% Total Drop Rate', "set": 'Events'},
    'xmasEvent2': {"name": 'Meaning of Giftmas', "per_tier": 1, "effect": '+% Money from Monsters', "set": 'Events'},
    'xmasEvent3': {"name": 'Golden Giftmas Box', "per_tier": 1, "effect": '+% Defence from Equipment', "set": 'Events'},
    'xmasEvent4': {"name": 'Big Ol Giftmas Box', "per_tier": 1, "effect": '+% Catching Away Gains', "set": 'Events'},
}
