"""Stamp cost/material metadata — vendored for the stamp recommender.

Source: IdleonToolbox data/website-data.json `stamps` (same provenance as
card_data / talent_data). Each list is one stamp tab; index i lines up with
the save's StampLevel[tab][i] (common.idleon_save.read_stamps). Fields drive
the gold/material upgrade-cost formulas (see stamp_recommender):
  base_coin/pow_coin   gold cost; pow_coin clamps low so gold is rarely the gate
  base_mat/pow_mat     material cost (the real gate at high levels)
  req_mult             reqItemMultiplicationLevel (levels per material step)
  mat_raw              material's rawName — matches storage ChestOrder entries
  mat_name             material display name
"""

STAMP_META: dict[str, list[dict]] = {
    "combat": [
        {'name': 'Sword Stamp', 'base_coin': 10, 'pow_coin': 1.2, 'base_mat': 3, 'pow_mat': 5, 'req_mult': 5, 'mat_raw': 'Grasslands1', 'mat_name': 'Spore Cap'},
        {'name': 'Heart Stamp', 'base_coin': 15, 'pow_coin': 1.2, 'base_mat': 5, 'pow_mat': 6, 'req_mult': 5, 'mat_raw': 'OakTree', 'mat_name': 'Oak Logs'},
        {'name': 'Mana Stamp', 'base_coin': 30, 'pow_coin': 1.2, 'base_mat': 6, 'pow_mat': 6, 'req_mult': 5, 'mat_raw': 'Copper', 'mat_name': 'Copper Ore'},
        {'name': 'Tomahawk Stamp', 'base_coin': 50, 'pow_coin': 1.3, 'base_mat': 5, 'pow_mat': 6, 'req_mult': 4, 'mat_raw': 'CopperBar', 'mat_name': 'Copper Bar'},
        {'name': 'Target Stamp', 'base_coin': 50, 'pow_coin': 1.3, 'base_mat': 5, 'pow_mat': 6, 'req_mult': 5, 'mat_raw': 'CraftMat1', 'mat_name': 'Thread'},
        {'name': 'Shield Stamp', 'base_coin': 50, 'pow_coin': 1.3, 'base_mat': 5, 'pow_mat': 7, 'req_mult': 5, 'mat_raw': 'Iron', 'mat_name': 'Iron Ore'},
        {'name': 'Longsword Stamp', 'base_coin': 50, 'pow_coin': 1.3, 'base_mat': 10, 'pow_mat': 6, 'req_mult': 4, 'mat_raw': 'Grasslands3', 'mat_name': 'Bean Slices'},
        {'name': 'Kapow Stamp', 'base_coin': 50, 'pow_coin': 1.3, 'base_mat': 20, 'pow_mat': 6, 'req_mult': 3, 'mat_raw': 'CraftMat5', 'mat_name': 'Trusty Nails'},
        {'name': 'Fist Stamp', 'base_coin': 50, 'pow_coin': 1.3, 'base_mat': 20, 'pow_mat': 7, 'req_mult': 2, 'mat_raw': 'BirchTree', 'mat_name': 'Bleach Logs'},
        {'name': 'Battleaxe Stamp', 'base_coin': 50, 'pow_coin': 1.3, 'base_mat': 15, 'pow_mat': 4, 'req_mult': 4, 'mat_raw': 'Leaf1', 'mat_name': 'Grass Leaf'},
        {'name': 'Agile Stamp', 'base_coin': 50, 'pow_coin': 1.3, 'base_mat': 1, 'pow_mat': 4, 'req_mult': 2, 'mat_raw': 'EquipmentToolsHatchet3', 'mat_name': 'Copper Chopper'},
        {'name': 'Vitality Stamp', 'base_coin': 50, 'pow_coin': 1.3, 'base_mat': 25, 'pow_mat': 6, 'req_mult': 4, 'mat_raw': 'Jungle2', 'mat_name': 'Snake Skin'},
        {'name': 'Book Stamp', 'base_coin': 50, 'pow_coin': 1.35, 'base_mat': 20, 'pow_mat': 5, 'req_mult': 2, 'mat_raw': 'IronBar', 'mat_name': 'Iron Bar'},
        {'name': 'Manamoar Stamp', 'base_coin': 75, 'pow_coin': 1.32, 'base_mat': 25, 'pow_mat': 6, 'req_mult': 3, 'mat_raw': 'Forest1', 'mat_name': 'Glublin Ear'},
        {'name': 'Clover Stamp', 'base_coin': 300, 'pow_coin': 1.38, 'base_mat': 1, 'pow_mat': 2, 'req_mult': 2, 'mat_raw': 'EquipmentShirts12', 'mat_name': 'Iron Platebody'},
        {'name': 'Scimitar Stamp', 'base_coin': 2000, 'pow_coin': 1.33, 'base_mat': 75, 'pow_mat': 7, 'req_mult': 4, 'mat_raw': 'Fish1', 'mat_name': 'Goldfish'},
        {'name': 'Bullseye Stamp', 'base_coin': 5000, 'pow_coin': 1.36, 'base_mat': 100, 'pow_mat': 10, 'req_mult': 5, 'mat_raw': 'Bug3', 'mat_name': 'Sentient Cereal'},
        {'name': 'Feather Stamp', 'base_coin': 2500, 'pow_coin': 1.3, 'base_mat': 25, 'pow_mat': 6, 'req_mult': 5, 'mat_raw': 'DesertB1', 'mat_name': 'Coconotnotto'},
        {'name': 'Polearm Stamp', 'base_coin': 3000, 'pow_coin': 1.3, 'base_mat': 1, 'pow_mat': 2, 'req_mult': 6, 'mat_raw': 'TestObj7', 'mat_name': 'Steel Axe'},
        {'name': 'Violence Stamp', 'base_coin': 10000, 'pow_coin': 1.3, 'base_mat': 10, 'pow_mat': 7, 'req_mult': 3, 'mat_raw': 'Dementia', 'mat_name': 'Dementia Ore'},
        {'name': 'Buckler Stamp', 'base_coin': 2200, 'pow_coin': 1.305, 'base_mat': 25, 'pow_mat': 6, 'req_mult': 7, 'mat_raw': 'PlatBar', 'mat_name': 'Platinum Bar'},
        {'name': 'Hermes Stamp', 'base_coin': 10000, 'pow_coin': 1.3, 'base_mat': 30, 'pow_mat': 7, 'req_mult': 3, 'mat_raw': 'Soul3', 'mat_name': 'Rooted Soul'},
        {'name': 'Sukka Foo', 'base_coin': 10000, 'pow_coin': 1.34, 'base_mat': 3, 'pow_mat': 5, 'req_mult': 10, 'mat_raw': 'Quest17', 'mat_name': 'Amarok Slab'},
        {'name': 'Arcane Stamp', 'base_coin': 1550, 'pow_coin': 1.36, 'base_mat': 50, 'pow_mat': 7, 'req_mult': 3, 'mat_raw': 'GoldBar', 'mat_name': 'Gold Bar'},
        {'name': 'Avast Yar Stamp', 'base_coin': 15000, 'pow_coin': 1.33, 'base_mat': 75, 'pow_mat': 7, 'req_mult': 5, 'mat_raw': 'Critter7', 'mat_name': 'Bunny'},
        {'name': 'Steve Sword', 'base_coin': 10000, 'pow_coin': 1.32, 'base_mat': 150, 'pow_mat': 5, 'req_mult': 10, 'mat_raw': 'Bug4', 'mat_name': 'Fruitfly'},
        {'name': 'Blover Stamp', 'base_coin': 25000, 'pow_coin': 1.39, 'base_mat': 100, 'pow_mat': 7, 'req_mult': 4, 'mat_raw': 'Fish3', 'mat_name': 'Jellyfish'},
        {'name': 'Stat Graph Stamp', 'base_coin': 2000, 'pow_coin': 1.36, 'base_mat': 2, 'pow_mat': 2, 'req_mult': 2, 'mat_raw': 'StoneZ1', 'mat_name': 'Mystery Upgrade Stone I'},
        {'name': 'Gilded Axe Stamp', 'base_coin': 2000000, 'pow_coin': 1.43, 'base_mat': 200, 'pow_mat': 6, 'req_mult': 6, 'mat_raw': 'CraftMat12', 'mat_name': 'Thingymabob'},
        {'name': 'Diamond Axe Stamp', 'base_coin': 3000000, 'pow_coin': 1.47, 'base_mat': 200, 'pow_mat': 6, 'req_mult': 10, 'mat_raw': 'CraftMat14', 'mat_name': 'PVC Pipe'},
        {'name': 'Tripleshot Stamp', 'base_coin': 1500000, 'pow_coin': 1.4, 'base_mat': 200, 'pow_mat': 6, 'req_mult': 10, 'mat_raw': 'CraftMat13', 'mat_name': 'Tangled Cords'},
        {'name': 'Blackheart Stamp', 'base_coin': 1000000, 'pow_coin': 1.4, 'base_mat': 200, 'pow_mat': 6, 'req_mult': 15, 'mat_raw': 'CraftMat11', 'mat_name': 'Purple Screw'},
        {'name': 'Maxo Slappo Stamp', 'base_coin': 100000000, 'pow_coin': 1.4, 'base_mat': 1000, 'pow_mat': 10, 'req_mult': 7, 'mat_raw': 'Tree9', 'mat_name': 'Maple Logs'},
        {'name': 'Sashe Sidestamp', 'base_coin': 100000000, 'pow_coin': 1.4, 'base_mat': 1000, 'pow_mat': 10, 'req_mult': 7, 'mat_raw': 'Bug9', 'mat_name': 'Scarab'},
        {'name': 'Intellectostampo', 'base_coin': 100000000, 'pow_coin': 1.4, 'base_mat': 150, 'pow_mat': 7, 'req_mult': 7, 'mat_raw': 'Soul6', 'mat_name': 'Oozie Soul'},
        {'name': 'Conjocharmo Stamp', 'base_coin': 100000000, 'pow_coin': 1.4, 'base_mat': 1000, 'pow_mat': 10, 'req_mult': 10, 'mat_raw': 'LavaA1', 'mat_name': 'Suggma Ashes'},
        {'name': 'Dementia Sword Stamp', 'base_coin': 200000000, 'pow_coin': 1.43, 'base_mat': 1000, 'pow_mat': 10, 'req_mult': 10, 'mat_raw': 'Dreadlo', 'mat_name': 'Dreadlo Ore'},
        {'name': 'Golden Sixes Stamp', 'base_coin': 10000000, 'pow_coin': 1.43, 'base_mat': 250, 'pow_mat': 10, 'req_mult': 10, 'mat_raw': 'Fish8', 'mat_name': 'Kraken'},
        {'name': 'Stat Wallstreet Stamp', 'base_coin': 25000000, 'pow_coin': 1.36, 'base_mat': 5, 'pow_mat': 2, 'req_mult': 2, 'mat_raw': 'StoneZ2', 'mat_name': 'Mystery Upgrade Stone II'},
        {'name': 'Void Sword Stamp', 'base_coin': 2500000000, 'pow_coin': 1.36, 'base_mat': 20000, 'pow_mat': 10, 'req_mult': 10, 'mat_raw': 'SpiA2', 'mat_name': 'Rice Cake'},
        {'name': 'Void Axe Stamp', 'base_coin': 66000000000, 'pow_coin': 1.36, 'base_mat': 25000, 'pow_mat': 10, 'req_mult': 15, 'mat_raw': 'Tree12', 'mat_name': 'Bamboo Logs'},
        {'name': 'Captalist Stats Stamp', 'base_coin': 2200000000000, 'pow_coin': 1.36, 'base_mat': 40000, 'pow_mat': 10, 'req_mult': 10, 'mat_raw': 'Bug13', 'mat_name': 'Firefly'},
        {'name': 'Splosion Stamp', 'base_coin': 660000000000000, 'pow_coin': 1.36, 'base_mat': 50000, 'pow_mat': 7, 'req_mult': 15, 'mat_raw': 'w7A3', 'mat_name': 'Earl Tail'},
        {'name': 'Gud EXP Stamp', 'base_coin': 66000000000000000, 'pow_coin': 1.45, 'base_mat': 250000, 'pow_mat': 12, 'req_mult': 15, 'mat_raw': 'w7A11', 'mat_name': 'Crabclaw'},
    ],
    "skills": [
        {'name': 'Pickaxe Stamp', 'base_coin': 10, 'pow_coin': 1.2, 'base_mat': 5, 'pow_mat': 4, 'req_mult': 10, 'mat_raw': 'OakTree', 'mat_name': 'Oak Logs'},
        {'name': 'Hatchet Stamp', 'base_coin': 10, 'pow_coin': 1.2, 'base_mat': 10, 'pow_mat': 4, 'req_mult': 10, 'mat_raw': 'CraftMat1', 'mat_name': 'Thread'},
        {'name': 'Anvil Zoomer Stamp', 'base_coin': 50, 'pow_coin': 1.3, 'base_mat': 25, 'pow_mat': 6, 'req_mult': 5, 'mat_raw': 'Copper', 'mat_name': 'Copper Ore'},
        {'name': "Lil' Mining Baggy Stamp", 'base_coin': 50, 'pow_coin': 1.3, 'base_mat': 25, 'pow_mat': 6, 'req_mult': 10, 'mat_raw': 'JungleTree', 'mat_name': 'Jungle Logs'},
        {'name': 'Twin Ores Stamp', 'base_coin': 10000, 'pow_coin': 1.3, 'base_mat': 1, 'pow_mat': 3, 'req_mult': 5, 'mat_raw': 'EquipmentHats3', 'mat_name': 'Thief Hood'},
        {'name': "Choppin' Bag Stamp", 'base_coin': 50, 'pow_coin': 1.3, 'base_mat': 25, 'pow_mat': 6, 'req_mult': 10, 'mat_raw': 'Jungle3', 'mat_name': 'Carrot Cube'},
        {'name': 'Duplogs Stamp', 'base_coin': 20000, 'pow_coin': 1.3, 'base_mat': 1, 'pow_mat': 3, 'req_mult': 5, 'mat_raw': 'EquipmentHats20', 'mat_name': 'Militia Helm'},
        {'name': 'Matty Bag Stamp', 'base_coin': 50, 'pow_coin': 1.3, 'base_mat': 1, 'pow_mat': 2, 'req_mult': 10, 'mat_raw': 'MaxCapBagM2', 'mat_name': 'Cramped Material Pouch'},
        {'name': 'Smart Dirt Stamp', 'base_coin': 80, 'pow_coin': 1.35, 'base_mat': 25, 'pow_mat': 6, 'req_mult': 5, 'mat_raw': 'Forest2', 'mat_name': 'Plank'},
        {'name': 'Cool Diggy Tool Stamp', 'base_coin': 35000, 'pow_coin': 1.4, 'base_mat': 1, 'pow_mat': 2, 'req_mult': 10, 'mat_raw': 'EquipmentToolsHatchet1', 'mat_name': 'Iron Hatchet'},
        {'name': 'High IQ Lumber Stamp', 'base_coin': 80, 'pow_coin': 1.35, 'base_mat': 25, 'pow_mat': 6, 'req_mult': 5, 'mat_raw': 'Forest3', 'mat_name': 'Bullfrog Horn'},
        {'name': 'Swag Swingy Tool Stamp', 'base_coin': 50000, 'pow_coin': 1.36, 'base_mat': 1, 'pow_mat': 2, 'req_mult': 10, 'mat_raw': 'EquipmentTools2', 'mat_name': 'Copper Pickaxe'},
        {'name': 'Alch Go Brrr Stamp', 'base_coin': 800, 'pow_coin': 1.29, 'base_mat': 40, 'pow_mat': 6, 'req_mult': 4, 'mat_raw': 'ForestTree', 'mat_name': 'Forest Fibres'},
        {'name': 'Brainstew Stamps', 'base_coin': 1250, 'pow_coin': 1.28, 'base_mat': 40, 'pow_mat': 6, 'req_mult': 5, 'mat_raw': 'Gold', 'mat_name': 'Gold Ore'},
        {'name': 'Drippy Drop Stamp', 'base_coin': 1000, 'pow_coin': 1.3, 'base_mat': 60, 'pow_mat': 6, 'req_mult': 5, 'mat_raw': 'DesertA1', 'mat_name': 'Pocket Sand'},
        {'name': 'Droplots Stamp', 'base_coin': 2500, 'pow_coin': 1.3, 'base_mat': 25, 'pow_mat': 4, 'req_mult': 2, 'mat_raw': 'Fish4', 'mat_name': 'Bloach'},
        {'name': 'Fishing Rod Stamp', 'base_coin': 1000, 'pow_coin': 1.32, 'base_mat': 50, 'pow_mat': 6, 'req_mult': 5, 'mat_raw': 'Bug1', 'mat_name': 'Fly'},
        {'name': 'Fishhead Stamp', 'base_coin': 1500, 'pow_coin': 1.33, 'base_mat': 55, 'pow_mat': 9, 'req_mult': 5, 'mat_raw': 'DesertA2', 'mat_name': 'Megalodon Tooth'},
        {'name': 'Catch Net Stamp', 'base_coin': 1000, 'pow_coin': 1.3, 'base_mat': 50, 'pow_mat': 6, 'req_mult': 5, 'mat_raw': 'Fish1', 'mat_name': 'Goldfish'},
        {'name': 'Fly Intel Stamp', 'base_coin': 1500, 'pow_coin': 1.33, 'base_mat': 40, 'pow_mat': 10, 'req_mult': 5, 'mat_raw': 'DesertA3', 'mat_name': 'Crabby Cakey'},
        {'name': 'Bag o Heads Stamp', 'base_coin': 1000, 'pow_coin': 1.3, 'base_mat': 35, 'pow_mat': 7, 'req_mult': 8, 'mat_raw': 'Bug2', 'mat_name': 'Butterfly'},
        {'name': 'Holy Mackerel Stamp', 'base_coin': 1500, 'pow_coin': 1.3, 'base_mat': 30, 'pow_mat': 6, 'req_mult': 5, 'mat_raw': 'Plat', 'mat_name': 'Platinum Ore'},
        {'name': 'Bugsack Stamp', 'base_coin': 1000, 'pow_coin': 1.3, 'base_mat': 35, 'pow_mat': 7, 'req_mult': 8, 'mat_raw': 'Fish2', 'mat_name': 'Hermit Can'},
        {'name': 'Buzz Buzz Stamp', 'base_coin': 1500, 'pow_coin': 1.3, 'base_mat': 45, 'pow_mat': 6, 'req_mult': 5, 'mat_raw': 'ToiletTree', 'mat_name': 'Potty Rolls'},
        {'name': 'Hidey Box Stamp', 'base_coin': 7500, 'pow_coin': 1.3, 'base_mat': 100, 'pow_mat': 5, 'req_mult': 10, 'mat_raw': 'Critter2', 'mat_name': 'Crabbo'},
        {'name': 'Purp Froge Stamp', 'base_coin': 10000, 'pow_coin': 1.3, 'base_mat': 125, 'pow_mat': 6, 'req_mult': 5, 'mat_raw': 'Critter3', 'mat_name': 'Scorpie'},
        {'name': 'Spikemouth Stamp', 'base_coin': 12500, 'pow_coin': 1.3, 'base_mat': 150, 'pow_mat': 6, 'req_mult': 3, 'mat_raw': 'Critter4', 'mat_name': 'Mousey'},
        {'name': 'Shiny Crab Stamp', 'base_coin': 15000, 'pow_coin': 1.3, 'base_mat': 200, 'pow_mat': 7, 'req_mult': 3, 'mat_raw': 'Critter5', 'mat_name': 'Owlio'},
        {'name': 'Gear Stamp', 'base_coin': 10000, 'pow_coin': 1.3, 'base_mat': 100, 'pow_mat': 5, 'req_mult': 3, 'mat_raw': 'SnowB1', 'mat_name': 'Sticky Stick'},
        {'name': 'Stample Stamp', 'base_coin': 10000, 'pow_coin': 1.3, 'base_mat': 100, 'pow_mat': 6, 'req_mult': 4, 'mat_raw': 'SnowA1', 'mat_name': 'Floof Ploof'},
        {'name': 'Saw Stamp', 'base_coin': 15000, 'pow_coin': 1.3, 'base_mat': 20, 'pow_mat': 5, 'req_mult': 3, 'mat_raw': 'DementiaBar', 'mat_name': 'Dementia Bar'},
        {'name': 'Amplestample Stamp', 'base_coin': 50000, 'pow_coin': 1.5, 'base_mat': 2500, 'pow_mat': 12, 'req_mult': 4, 'mat_raw': 'Bug5', 'mat_name': 'Mosquisnow'},
        {'name': 'SpoOoky Stamp', 'base_coin': 7500, 'pow_coin': 1.3, 'base_mat': 45, 'pow_mat': 6, 'req_mult': 10, 'mat_raw': 'Soul1', 'mat_name': 'Forest Soul'},
        {'name': 'Flowin Stamp', 'base_coin': 15000, 'pow_coin': 1.3, 'base_mat': 2, 'pow_mat': 5, 'req_mult': 2, 'mat_raw': 'Refinery1', 'mat_name': 'Redox Salts'},
        {'name': 'Prayday Stamp', 'base_coin': 10000, 'pow_coin': 1.3, 'base_mat': 150, 'pow_mat': 6, 'req_mult': 2, 'mat_raw': 'SnowB4', 'mat_name': 'Cracked Glass'},
        {'name': 'Banked Pts Stamp', 'base_coin': 6000, 'pow_coin': 1.3, 'base_mat': 100, 'pow_mat': 3, 'req_mult': 6, 'mat_raw': 'Soul2', 'mat_name': 'Dune Soul'},
        {'name': 'Cooked Meal Stamp', 'base_coin': 1000000, 'pow_coin': 1.35, 'base_mat': 200, 'pow_mat': 5, 'req_mult': 15, 'mat_raw': 'Fish5', 'mat_name': 'Skelefish'},
        {'name': 'Spice Stamp', 'base_coin': 1000000, 'pow_coin': 1.35, 'base_mat': 200, 'pow_mat': 5, 'req_mult': 15, 'mat_raw': 'GalaxyA1', 'mat_name': 'Purple Mush Cap'},
        {'name': 'Ladle Stamp', 'base_coin': 1000000, 'pow_coin': 1.35, 'base_mat': 200, 'pow_mat': 5, 'req_mult': 10, 'mat_raw': 'Fish6', 'mat_name': 'Sand Shark'},
        {'name': 'Nest Eggs Stamp', 'base_coin': 1000000, 'pow_coin': 1.4, 'base_mat': 200, 'pow_mat': 5, 'req_mult': 10, 'mat_raw': 'AlienTree', 'mat_name': 'Alien Hive Chunk'},
        {'name': 'Egg Stamp', 'base_coin': 1000000, 'pow_coin': 1.4, 'base_mat': 200, 'pow_mat': 5, 'req_mult': 15, 'mat_raw': 'GalaxyA3', 'mat_name': 'Half Eaten Donut'},
        {'name': 'Lab Tube Stamp', 'base_coin': 1000000, 'pow_coin': 1.35, 'base_mat': 200, 'pow_mat': 5, 'req_mult': 10, 'mat_raw': 'GalaxyB1', 'mat_name': 'Bottle Cap'},
        {'name': 'Sailboat Stamp', 'base_coin': 500000000, 'pow_coin': 1.35, 'base_mat': 1000, 'pow_mat': 5, 'req_mult': 5, 'mat_raw': 'LavaA5', 'mat_name': 'Stilt Pole'},
        {'name': 'Gamejoy Stamp', 'base_coin': 500000000, 'pow_coin': 1.35, 'base_mat': 500, 'pow_mat': 8, 'req_mult': 5, 'mat_raw': 'Tree10', 'mat_name': 'Dandielogs'},
        {'name': 'Divine Stamp', 'base_coin': 500000000, 'pow_coin': 1.35, 'base_mat': 1000, 'pow_mat': 10, 'req_mult': 8, 'mat_raw': 'LavaB3', 'mat_name': 'Orange Slice'},
        {'name': 'Multitool Stamp', 'base_coin': 800000000, 'pow_coin': 1.35, 'base_mat': 500, 'pow_mat': 8, 'req_mult': 10, 'mat_raw': 'Bug10', 'mat_name': 'Dust Mote'},
        {'name': 'Skelefish Stamp', 'base_coin': 800000000, 'pow_coin': 1.35, 'base_mat': 250, 'pow_mat': 10, 'req_mult': 2, 'mat_raw': 'Fish5', 'mat_name': 'Skelefish'},
        {'name': 'Crop Evo Stamp', 'base_coin': 100000000000, 'pow_coin': 1.37, 'base_mat': 12000, 'pow_mat': 10, 'req_mult': 5, 'mat_raw': 'Fish9', 'mat_name': 'Icefish'},
        {'name': 'Sneaky Peeky Stamp', 'base_coin': 50000000000, 'pow_coin': 1.37, 'base_mat': 20000, 'pow_mat': 10, 'req_mult': 8, 'mat_raw': 'SpiA4', 'mat_name': 'Leafy Horn'},
        {'name': 'Jade Mint Stamp', 'base_coin': 20000000000, 'pow_coin': 1.37, 'base_mat': 15, 'pow_mat': 7, 'req_mult': 10, 'mat_raw': 'SpiA2b', 'mat_name': 'Stacked Rice Cake'},
        {'name': 'Summoner Stone Stamp', 'base_coin': 50000000000, 'pow_coin': 1.37, 'base_mat': 8000, 'pow_mat': 10, 'req_mult': 8, 'mat_raw': 'Soul7', 'mat_name': 'Breezy Soul'},
        {'name': 'White Essence Stamp', 'base_coin': 60000000000, 'pow_coin': 1.37, 'base_mat': 15000, 'pow_mat': 10, 'req_mult': 8, 'mat_raw': 'Bug12', 'mat_name': 'Ladybug'},
        {'name': 'Triad Essence Stamp', 'base_coin': 800000000000, 'pow_coin': 1.37, 'base_mat': 8000, 'pow_mat': 10, 'req_mult': 8, 'mat_raw': 'Fish12', 'mat_name': 'Caulifish'},
        {'name': 'Dark Triad Essence Stamp', 'base_coin': 12000000000000, 'pow_coin': 1.37, 'base_mat': 45000, 'pow_mat': 10, 'req_mult': 8, 'mat_raw': 'Tree13', 'mat_name': 'Effervescent Logs'},
        {'name': 'Amber Stamp', 'base_coin': 1200000000000000, 'pow_coin': 1.37, 'base_mat': 500, 'pow_mat': 10, 'req_mult': 8, 'mat_raw': 'Spelunking1', 'mat_name': "Chapter Two 'Decay Surrounds'"},
        {'name': 'Little Rock Stamp', 'base_coin': 1200000000000000, 'pow_coin': 1.37, 'base_mat': 100, 'pow_mat': 10, 'req_mult': 8, 'mat_raw': 'Spelunking0', 'mat_name': "Chapter One 'The Fear Within'"},
        {'name': 'Hardhat Stamp', 'base_coin': 1200000000000000, 'pow_coin': 1.37, 'base_mat': 100, 'pow_mat': 10, 'req_mult': 8, 'mat_raw': 'Spelunking2', 'mat_name': "Chapter Three 'This is Gospel'"},
    ],
    "misc": [
        {'name': 'Questin Stamp', 'base_coin': 500, 'pow_coin': 1.32, 'base_mat': 30, 'pow_mat': 6, 'req_mult': 10, 'mat_raw': 'Jungle1', 'mat_name': 'Slime Sludge'},
        {'name': 'Mason Jar Stamp', 'base_coin': 4000, 'pow_coin': 1.28, 'base_mat': 1, 'pow_mat': 3, 'req_mult': 4, 'mat_raw': 'DesertA1b', 'mat_name': 'Glass Shard'},
        {'name': 'Crystallin', 'base_coin': 800, 'pow_coin': 1.31, 'base_mat': 35, 'pow_mat': 8, 'req_mult': 10, 'mat_raw': 'CraftMat6', 'mat_name': 'Boring Brick'},
        {'name': 'Arcade Ball Stamp', 'base_coin': 1500, 'pow_coin': 1.33, 'base_mat': 30, 'pow_mat': 6, 'req_mult': 10, 'mat_raw': 'Copper', 'mat_name': 'Copper Ore'},
        {'name': 'Gold Ball Stamp', 'base_coin': 1000, 'pow_coin': 1.33, 'base_mat': 50, 'pow_mat': 6.5, 'req_mult': 10, 'mat_raw': 'Fish1', 'mat_name': 'Goldfish'},
        {'name': 'Potion Stamp', 'base_coin': 1500, 'pow_coin': 1.305, 'base_mat': 50, 'pow_mat': 8, 'req_mult': 5, 'mat_raw': 'FoodMining1', 'mat_name': 'Icing Ironbite'},
        {'name': 'Golden Apple Stamp', 'base_coin': 3000, 'pow_coin': 1.3, 'base_mat': 2, 'pow_mat': 4, 'req_mult': 4, 'mat_raw': 'FoodG4', 'mat_name': 'Golden Nomwich'},
        {'name': 'Ball Timer Stamp', 'base_coin': 1000, 'pow_coin': 1.32, 'base_mat': 100, 'pow_mat': 15, 'req_mult': 5, 'mat_raw': 'OakTree', 'mat_name': 'Oak Logs'},
        {'name': 'Card Stamp', 'base_coin': 1200, 'pow_coin': 1.31, 'base_mat': 25, 'pow_mat': 6, 'req_mult': 10, 'mat_raw': 'DesertB2', 'mat_name': 'Furled Flag'},
        {'name': 'Forge Stamp', 'base_coin': 5000000000000, 'pow_coin': 1.3, 'base_mat': 250, 'pow_mat': 8, 'req_mult': 10, 'mat_raw': 'Godshard', 'mat_name': 'Godshard Ore'},
        {'name': 'Vendor Stamp', 'base_coin': 30000, 'pow_coin': 1.5, 'base_mat': 100, 'pow_mat': 10, 'req_mult': 10, 'mat_raw': 'CraftMat3', 'mat_name': 'Cue Tape'},
        {'name': 'Sigil Stamp', 'base_coin': 1000000, 'pow_coin': 1.32, 'base_mat': 2000, 'pow_mat': 6, 'req_mult': 12, 'mat_raw': 'SnowA4', 'mat_name': 'Ram Wool'},
        {'name': 'Talent I Stamp', 'base_coin': 2000, 'pow_coin': 1.4, 'base_mat': 50, 'pow_mat': 10, 'req_mult': 2, 'mat_raw': 'Grasslands2', 'mat_name': 'Frog Leg'},
        {'name': 'Talent II Stamp', 'base_coin': 4000, 'pow_coin': 1.35, 'base_mat': 200, 'pow_mat': 8, 'req_mult': 2, 'mat_raw': 'DesertB3', 'mat_name': 'Pincer Arm'},
        {'name': 'Talent III Stamp', 'base_coin': 40000, 'pow_coin': 1.35, 'base_mat': 20, 'pow_mat': 4, 'req_mult': 2, 'mat_raw': 'Leaf3', 'mat_name': 'Arctic Leaf'},
        {'name': 'Talent IV Stamp', 'base_coin': 300000000, 'pow_coin': 1.4, 'base_mat': 2, 'pow_mat': 3, 'req_mult': 2, 'mat_raw': 'LavaA1b', 'mat_name': 'Royal Suggma Urn'},
        {'name': 'Talent V Stamp', 'base_coin': 50, 'pow_coin': 1.3, 'base_mat': 25, 'pow_mat': 6, 'req_mult': 2, 'mat_raw': 'Copper', 'mat_name': 'Copper Ore'},
        {'name': 'Talent S Stamp', 'base_coin': 50, 'pow_coin': 1.3, 'base_mat': 20, 'pow_mat': 4, 'req_mult': 2, 'mat_raw': 'Leaf2', 'mat_name': 'Twisty Leaf'},
        {'name': 'Multikill Stamp', 'base_coin': 10000, 'pow_coin': 1.3, 'base_mat': 100, 'pow_mat': 3, 'req_mult': 2, 'mat_raw': 'Grasslands1', 'mat_name': 'Spore Cap'},
        {'name': 'Biblio Stamp', 'base_coin': 12500, 'pow_coin': 1.3, 'base_mat': 125, 'pow_mat': 5, 'req_mult': 2, 'mat_raw': 'SaharanFoal', 'mat_name': 'Tundra Logs'},
        {'name': 'DNA Stamp', 'base_coin': 1000000, 'pow_coin': 1.6, 'base_mat': 200, 'pow_mat': 5, 'req_mult': 3, 'mat_raw': 'Bug7', 'mat_name': 'Worker Bee'},
        {'name': 'Refinery Stamp', 'base_coin': 25000000, 'pow_coin': 1.52, 'base_mat': 250, 'pow_mat': 5, 'req_mult': 5, 'mat_raw': 'LavaA4', 'mat_name': 'Cheesy Crumbs'},
        {'name': 'Atomic Stamp', 'base_coin': 25000000, 'pow_coin': 1.52, 'base_mat': 2500, 'pow_mat': 5, 'req_mult': 8, 'mat_raw': 'SpiA3', 'mat_name': 'Bamboo'},
        {'name': 'Cavern Resource Stamp', 'base_coin': 2000000000, 'pow_coin': 1.72, 'base_mat': 10, 'pow_mat': 20, 'req_mult': 20, 'mat_raw': 'Ladle', 'mat_name': 'Cooking Ladle'},
        {'name': 'Study Hall Stamp', 'base_coin': 2000000000, 'pow_coin': 1.72, 'base_mat': 30, 'pow_mat': 20, 'req_mult': 15, 'mat_raw': 'EquipmentStatues29', 'mat_name': 'Villager Statue'},
        {'name': 'Kruker Stamp', 'base_coin': 2000000000000000000, 'pow_coin': 4.5, 'base_mat': 20000, 'pow_mat': 100, 'req_mult': 1, 'mat_raw': 'w7A1', 'mat_name': 'Equinox Flesh'},
        {'name': 'Corale Stamp', 'base_coin': 20000000000000, 'pow_coin': 1.72, 'base_mat': 2500, 'pow_mat': 10, 'req_mult': 15, 'mat_raw': 'w7A9', 'mat_name': 'Demonflesh'},
    ],
}
