# ui/launcher/talent_data.py  -- sourced for #44; see issue for provenance.
#
# index (SkillLevels array position / talent UID) -> talent metadata.
#
# Source of the index->name correspondence: Morta1/IdleonToolbox builds.json
# (every talent object carries a `skillIndex` = its SkillLevels array slot).
# Class assigned by index-block (talent pages map to class lines), verified
# against the local save: each character's active SkillLevelsMAX indices fall
# in the block of its CharacterClass line (Warrior 81-149 / Archer 263-328 /
# Mage 445-539, Beginner 0-79, Special/Star 15-59).
#
# importance: 1=weapon-power/AFK-gain, 2=weapon-power/equipment-stat%,
#             3=primary class stat / default, 4=low value (LUK/HP/Mana).
# bookable:   False only for talents whose cap is raised by a tab-3 talent
#             (cannot be booked from the Library) -- see issue #44.
#
# NOT covered (no authoritative index->name source found): the shared
# special/star-talent block at indices 618-658 (active on every character
# regardless of class; caps up to 121). Left out rather than guessed.

# CharacterClass int -> class name. The save's per-character
# `CharacterClass` is a direct index into IdleonToolbox's `classes` array
# (data/website-data.json; `character.classIndex = char.CharacterClass`),
# so this is that array with the non-class slots (skills / "Nope" fillers /
# the *_Basics rows) dropped. Verified against the local save: the seven
# characters read 8/9 (Barbarian/Squire), 20/21 (Bowman/Hunter), 31/32/33
# (Mage/Wizard/Shaman) — note the Mage line does NOT follow the Warrior/
# Archer "base, +1=W2, +2=W3" ordering (Wizard=32 precedes Shaman=33), so
# the numbers come from the authoritative array, not an inferred pattern.
CLASS_BY_ID: dict[int, str] = {
    1: "Beginner", 2: "Journeyman", 3: "Maestro", 4: "Voidwalker", 5: "Infinilyte",
    7: "Warrior", 8: "Barbarian", 9: "Squire", 10: "Blood Berserker",
    12: "Divine Knight", 14: "Death Bringer", 16: "Royal Guardian",
    19: "Archer", 20: "Bowman", 21: "Hunter", 22: "Siege Breaker",
    25: "Beast Master", 29: "Wind Walker",
    31: "Mage", 32: "Wizard", 33: "Shaman", 34: "Elemental Sorcerer",
    35: "Spiritual Monk", 36: "Bubonic Conjuror", 40: "Arcane Cultist",
}


def class_name(class_id: int | None) -> str:
    """Human class name for a save `CharacterClass` int, or `Class <id>`
    when the id isn't a known class (future/secret classes degrade
    gracefully rather than hiding the raw number)."""
    if class_id is None:
        return "?"
    return CLASS_BY_ID.get(int(class_id), f"Class {int(class_id)}")


# Class line -> its base class (the Talent Book Library "genre"). The Library
# is browsed base-class (genre) -> subclass (subgenre), so a book's genre is
# the base class its talent's class line descends from. Every class in the
# evolution tree folds onto Beginner / Warrior / Archer / Mage; "Special"
# (the star-talent block) is its own genre — those live in the VIP Bookshelf,
# not a class line.
CLASS_GENRE: dict[str, str] = {
    "Beginner": "Beginner", "Journeyman": "Beginner", "Maestro": "Beginner",
    "Voidwalker": "Beginner", "Infinilyte": "Beginner",
    "Special": "Special",
    "Warrior": "Warrior", "Barbarian": "Warrior", "Squire": "Warrior",
    "Blood Berserker": "Warrior", "Divine Knight": "Warrior",
    "Death Bringer": "Warrior", "Royal Guardian": "Warrior",
    "Archer": "Archer", "Bowman": "Archer", "Hunter": "Archer",
    "Siege Breaker": "Archer", "Beast Master": "Archer", "Wind Walker": "Archer",
    "Mage": "Mage", "Wizard": "Mage", "Shaman": "Mage",
    "Elemental Sorcerer": "Mage", "Spiritual Monk": "Mage",
    "Bubonic Conjuror": "Mage", "Arcane Cultist": "Mage",
}


def base_genre(class_line: str | None) -> str:
    """Library genre (base class) for a talent's class line. Unknown lines
    fall back to themselves, so an unmapped class degrades to genre==subgenre
    rather than vanishing."""
    if class_line is None:
        return "?"
    return CLASS_GENRE.get(class_line, class_line)


TALENT_META: dict[int, dict] = {
    0: {"name": 'Health Booster', "class": 'Beginner', "tab": 0, "importance": 4, "bookable": True},
    1: {"name": 'Mana Booster', "class": 'Beginner', "tab": 0, "importance": 4, "bookable": True},
    5: {"name": 'Sharpened Axe', "class": 'Beginner', "tab": 0, "importance": 1, "bookable": True},
    6: {"name": 'Gilded Sword', "class": 'Beginner', "tab": 0, "importance": 1, "bookable": True},
    8: {"name": 'Star Player', "class": 'Beginner', "tab": 0, "importance": 3, "bookable": True},
    9: {"name": 'Bucklered Up', "class": 'Beginner', "tab": 0, "importance": 3, "bookable": True},
    10: {"name": 'Fist Of Rage', "class": 'Beginner', "tab": 0, "importance": 3, "bookable": False},
    11: {"name": 'Quickness Boots', "class": 'Beginner', "tab": 0, "importance": 3, "bookable": False},
    12: {"name": 'Book Of The Wise', "class": 'Beginner', "tab": 0, "importance": 3, "bookable": False},
    13: {"name": 'Lucky Clover', "class": 'Beginner', "tab": 0, "importance": 4, "bookable": True},
    15: {"name": 'Indiana Attack', "class": 'Special', "tab": 0, "importance": 3, "bookable": True},
    16: {"name": "Breakin' The Bank", "class": 'Special', "tab": 0, "importance": 3, "bookable": True},
    17: {"name": 'Supernova Player', "class": 'Special', "tab": 0, "importance": 3, "bookable": True},
    18: {"name": 'Two Punch Man', "class": 'Special', "tab": 0, "importance": 2, "bookable": True},
    19: {"name": 'Gimme Gimme', "class": 'Special', "tab": 0, "importance": 3, "bookable": True},
    20: {"name": 'Lucky Hit', "class": 'Special', "tab": 0, "importance": 4, "bookable": True},
    21: {"name": "F'luk'ey Fabrics", "class": 'Special', "tab": 0, "importance": 3, "bookable": True},
    22: {"name": 'Chaching!', "class": 'Special', "tab": 0, "importance": 3, "bookable": True},
    23: {"name": 'Lucky Horseshoe', "class": 'Special', "tab": 0, "importance": 4, "bookable": False},
    24: {"name": 'Curse Of Mr Looty Booty', "class": 'Special', "tab": 0, "importance": 3, "bookable": True},
    25: {"name": 'Its Your Birthday!', "class": 'Special', "tab": 0, "importance": 3, "bookable": True},
    26: {"name": 'Cmon Out Crystals', "class": 'Special', "tab": 0, "importance": 3, "bookable": True},
    27: {"name": 'Reroll Pls', "class": 'Special', "tab": 0, "importance": 3, "bookable": True},
    28: {"name": 'Cards Galore', "class": 'Special', "tab": 0, "importance": 3, "bookable": True},
    29: {"name": 'Rares Everywhere!', "class": 'Special', "tab": 0, "importance": 3, "bookable": True},
    30: {"name": 'Coin Toss', "class": 'Special', "tab": 0, "importance": 3, "bookable": True},
    31: {"name": 'Skillage Damage', "class": 'Special', "tab": 0, "importance": 3, "bookable": True},
    32: {"name": 'Printer Go Brrr', "class": 'Special', "tab": 0, "importance": 3, "bookable": True},
    33: {"name": 'Triple Jab', "class": 'Special', "tab": 0, "importance": 2, "bookable": True},
    34: {"name": 'One Step Ahead', "class": 'Special', "tab": 0, "importance": 3, "bookable": True},
    35: {"name": 'Lucky Charms', "class": 'Special', "tab": 0, "importance": 4, "bookable": True},
    36: {"name": 'Clever Clover Obols', "class": 'Special', "tab": 0, "importance": 3, "bookable": True},
    37: {"name": 'Skilliest Statue', "class": 'Special', "tab": 0, "importance": 3, "bookable": True},
    38: {"name": 'Bliss N Chips', "class": 'Special', "tab": 0, "importance": 3, "bookable": True},
    39: {"name": 'Colloquial Containers', "class": 'Special', "tab": 0, "importance": 3, "bookable": True},
    40: {"name": 'Maestro Transfusion', "class": 'Special', "tab": 0, "importance": 1, "bookable": True},
    41: {"name": 'Crystal Countdown', "class": 'Special', "tab": 0, "importance": 1, "bookable": True},
    42: {"name": 'Left Hand Of Learning', "class": 'Special', "tab": 0, "importance": 1, "bookable": True},
    43: {"name": 'Right Hand Of Action', "class": 'Special', "tab": 0, "importance": 1, "bookable": True},
    44: {"name": 'Jman Was Better', "class": 'Special', "tab": 0, "importance": 3, "bookable": True},
    45: {"name": 'Void Trial Rerun', "class": 'Maestro', "tab": 0, "importance": 3, "bookable": True},
    46: {"name": 'Void Radius', "class": 'Maestro', "tab": 0, "importance": 3, "bookable": True},
    47: {"name": 'Bossing Vain', "class": 'Maestro', "tab": 0, "importance": 3, "bookable": True},
    48: {"name": 'Quad Jab', "class": 'Maestro', "tab": 0, "importance": 2, "bookable": True},
    49: {"name": 'Enhancement Eclipse', "class": 'Maestro', "tab": 0, "importance": 3, "bookable": True},
    50: {"name": 'Power Orb', "class": 'Maestro', "tab": 0, "importance": 3, "bookable": True},
    51: {"name": 'Eternal Str', "class": 'Maestro', "tab": 0, "importance": 3, "bookable": True},
    52: {"name": 'Eternal Agi', "class": 'Maestro', "tab": 0, "importance": 3, "bookable": True},
    53: {"name": 'Eternal Wis', "class": 'Maestro', "tab": 0, "importance": 3, "bookable": True},
    54: {"name": 'Eternal Luk', "class": 'Maestro', "tab": 0, "importance": 3, "bookable": True},
    55: {"name": 'Exp Cultivation', "class": 'Maestro', "tab": 0, "importance": 3, "bookable": True},
    56: {"name": 'Voodoo Statufication', "class": 'Maestro', "tab": 0, "importance": 3, "bookable": True},
    57: {"name": 'Species Epoch', "class": 'Maestro', "tab": 0, "importance": 3, "bookable": True},
    58: {"name": 'Master Of The System', "class": 'Maestro', "tab": 0, "importance": 3, "bookable": True},
    59: {"name": 'Blood Marrow', "class": 'Maestro', "tab": 0, "importance": 3, "bookable": True},
    75: {"name": 'Happy Dude', "class": 'Beginner', "tab": 0, "importance": 3, "bookable": False},
    76: {"name": 'Knucklebuster', "class": 'Beginner', "tab": 0, "importance": 3, "bookable": True},
    77: {"name": 'Feather Flight', "class": 'Beginner', "tab": 0, "importance": 3, "bookable": True},
    78: {"name": 'Extra Bags', "class": 'Beginner', "tab": 0, "importance": 3, "bookable": True},
    79: {"name": "Sleepin' On The Job", "class": 'Beginner', "tab": 0, "importance": 3, "bookable": False},
    81: {"name": 'Str Summore', "class": 'Warrior', "tab": 0, "importance": 1, "bookable": True},
    85: {"name": 'Brute Efficiency', "class": 'Warrior', "tab": 0, "importance": 1, "bookable": True},
    86: {"name": 'Meat Shank', "class": 'Warrior', "tab": 0, "importance": 3, "bookable": False},
    87: {"name": 'Critikill', "class": 'Warrior', "tab": 0, "importance": 3, "bookable": False},
    88: {"name": 'Idle Brawling', "class": 'Warrior', "tab": 0, "importance": 1, "bookable": True},
    89: {"name": 'Idle Skilling', "class": 'Warrior', "tab": 0, "importance": 1, "bookable": True},
    90: {"name": 'Power Strike', "class": 'Warrior', "tab": 0, "importance": 1, "bookable": True},
    91: {"name": 'Whirl', "class": 'Warrior', "tab": 0, "importance": 2, "bookable": True},
    92: {"name": 'Health Overdrive', "class": 'Warrior', "tab": 0, "importance": 4, "bookable": True},
    93: {"name": 'Double Strike', "class": 'Warrior', "tab": 0, "importance": 2, "bookable": True},
    94: {"name": 'Firmly Grasp It', "class": 'Warrior', "tab": 0, "importance": 2, "bookable": True},
    95: {"name": 'Strength In Numbers', "class": 'Warrior', "tab": 0, "importance": 2, "bookable": True},
    96: {"name": "'str'ess Tested Garb", "class": 'Warrior', "tab": 0, "importance": 2, "bookable": True},
    97: {"name": 'Carry A Big Stick', "class": 'Warrior', "tab": 0, "importance": 2, "bookable": True},
    98: {"name": 'Absolute Unit', "class": 'Warrior', "tab": 0, "importance": 2, "bookable": True},
    99: {"name": 'Haungry For Gold', "class": 'Warrior', "tab": 0, "importance": 3, "bookable": True},
    100: {"name": 'Big Pick', "class": 'Warrior', "tab": 0, "importance": 3, "bookable": True},
    101: {"name": 'Copper Collector', "class": 'Warrior', "tab": 0, "importance": 3, "bookable": True},
    102: {"name": 'Motherlode Miner', "class": 'Warrior', "tab": 0, "importance": 3, "bookable": True},
    103: {"name": 'Tool Proficiency', "class": 'Warrior', "tab": 0, "importance": 3, "bookable": True},
    104: {"name": 'Tempestuous Emotions', "class": 'Warrior', "tab": 0, "importance": 1, "bookable": True},
    105: {"name": 'Bear Swipe', "class": 'Warrior', "tab": 0, "importance": 3, "bookable": True},
    106: {"name": 'Axe Hurl', "class": 'Warrior', "tab": 0, "importance": 3, "bookable": True},
    107: {"name": 'Mocking Shout', "class": 'Warrior', "tab": 0, "importance": 3, "bookable": True},
    108: {"name": 'No Pain No Gain', "class": 'Warrior', "tab": 0, "importance": 3, "bookable": True},
    109: {"name": 'Monster Decimator', "class": 'Warrior', "tab": 0, "importance": 3, "bookable": True},
    110: {"name": 'Apocalypse Zow', "class": 'Warrior', "tab": 0, "importance": 3, "bookable": True},
    111: {"name": 'Fistful Of Obol', "class": 'Warrior', "tab": 0, "importance": 3, "bookable": True},
    112: {"name": 'Strongest Statues', "class": 'Warrior', "tab": 0, "importance": 3, "bookable": True},
    114: {"name": 'Beefy Bottles', "class": 'Barbarian', "tab": 0, "importance": 3, "bookable": True},
    115: {"name": 'Worming Undercover', "class": 'Barbarian', "tab": 0, "importance": 3, "bookable": True},
    116: {"name": "Bobbin' Bobbers", "class": 'Barbarian', "tab": 0, "importance": 3, "bookable": True},
    117: {"name": 'All Fish Diet', "class": 'Barbarian', "tab": 0, "importance": 3, "bookable": True},
    118: {"name": "Catching Some Zzz's", "class": 'Barbarian', "tab": 0, "importance": 3, "bookable": True},
    119: {"name": 'Back To Basics', "class": 'Barbarian', "tab": 0, "importance": 3, "bookable": True},
    120: {"name": 'Shockwave Slash', "class": 'Barbarian', "tab": 0, "importance": 2, "bookable": True},
    121: {"name": 'Daggerang', "class": 'Barbarian', "tab": 0, "importance": 3, "bookable": True},
    122: {"name": 'Bricky Skin', "class": 'Barbarian', "tab": 0, "importance": 3, "bookable": True},
    123: {"name": 'Mastery Up', "class": 'Barbarian', "tab": 0, "importance": 3, "bookable": True},
    124: {"name": 'Balanced Spirit', "class": 'Barbarian', "tab": 0, "importance": 3, "bookable": True},
    125: {"name": 'Precision Power', "class": 'Barbarian', "tab": 0, "importance": 3, "bookable": True},
    127: {"name": 'Shieldiest Statues', "class": 'Barbarian', "tab": 0, "importance": 3, "bookable": True},
    129: {"name": 'Blocky Bottles', "class": 'Barbarian', "tab": 0, "importance": 3, "bookable": True},
    130: {"name": 'Refinery Throttle', "class": 'Barbarian', "tab": 0, "importance": 3, "bookable": True},
    131: {"name": 'Redox Rates', "class": 'Barbarian', "tab": 0, "importance": 3, "bookable": True},
    132: {"name": 'Sharper Saws', "class": 'Barbarian', "tab": 0, "importance": 3, "bookable": True},
    133: {"name": 'Super Samples', "class": 'Barbarian', "tab": 0, "importance": 3, "bookable": True},
    135: {"name": 'Fired Up', "class": 'Barbarian', "tab": 0, "importance": 3, "bookable": True},
    136: {"name": 'Combustion', "class": 'Barbarian', "tab": 0, "importance": 3, "bookable": True},
    137: {"name": 'Serrated Swipe', "class": 'Barbarian', "tab": 0, "importance": 2, "bookable": True},
    138: {"name": 'Ember Bear', "class": 'Barbarian', "tab": 0, "importance": 3, "bookable": True},
    139: {"name": 'Ferocity Strike', "class": 'Barbarian', "tab": 0, "importance": 2, "bookable": True},
    140: {"name": 'Tough Steaks', "class": 'Barbarian', "tab": 0, "importance": 4, "bookable": True},
    141: {"name": 'Charred Skulls', "class": 'Barbarian', "tab": 0, "importance": 3, "bookable": True},
    142: {"name": 'Skill Strengthen', "class": 'Barbarian', "tab": 0, "importance": 3, "bookable": True},
    143: {"name": 'Overblown Testosterone', "class": 'Barbarian', "tab": 0, "importance": 3, "bookable": True},
    144: {"name": 'The Family Guy', "class": 'Barbarian', "tab": 0, "importance": 3, "bookable": True},
    145: {"name": 'Taste Test', "class": 'Barbarian', "tab": 0, "importance": 3, "bookable": True},
    146: {"name": 'Apocalypse Chow', "class": 'Barbarian', "tab": 0, "importance": 3, "bookable": True},
    147: {"name": 'Waiting To Cool', "class": 'Barbarian', "tab": 0, "importance": 3, "bookable": True},
    148: {"name": 'Overflowing Ladle', "class": 'Barbarian', "tab": 0, "importance": 3, "bookable": True},
    149: {"name": 'Symbols Of Beyond ~r', "class": 'Barbarian', "tab": 0, "importance": 3, "bookable": True},
    165: {"name": 'Knightly Disciple', "class": 'Squire', "tab": 0, "importance": 3, "bookable": True},
    166: {"name": 'Mega Mongorang', "class": 'Squire', "tab": 0, "importance": 3, "bookable": True},
    167: {"name": 'Divine Intervention', "class": 'Squire', "tab": 0, "importance": 3, "bookable": True},
    168: {"name": 'Orb Of Remembrance', "class": 'Squire', "tab": 0, "importance": 3, "bookable": True},
    169: {"name": 'Imbued Shockwaves', "class": 'Squire', "tab": 0, "importance": 3, "bookable": True},
    170: {"name": 'Gamer Strength', "class": 'Squire', "tab": 0, "importance": 3, "bookable": True},
    175: {"name": 'Undying Passion', "class": 'Squire', "tab": 0, "importance": 3, "bookable": True},
    176: {"name": '1000 Hours Played', "class": 'Squire', "tab": 0, "importance": 3, "bookable": True},
    177: {"name": 'Bitty Litty', "class": 'Squire', "tab": 0, "importance": 3, "bookable": True},
    178: {"name": 'King Of The Remembered', "class": 'Squire', "tab": 0, "importance": 3, "bookable": True},
    195: {"name": 'Wraith Form', "class": 'Blood Berserker', "tab": 0, "importance": 3, "bookable": True},
    196: {"name": 'Grimoire', "class": 'Blood Berserker', "tab": 0, "importance": 3, "bookable": True},
    197: {"name": 'Sentinel Axes', "class": 'Blood Berserker', "tab": 0, "importance": 3, "bookable": True},
    198: {"name": 'Graveyard Shift', "class": 'Blood Berserker', "tab": 0, "importance": 3, "bookable": True},
    199: {"name": 'Detonation', "class": 'Blood Berserker', "tab": 0, "importance": 3, "bookable": True},
    200: {"name": 'Marauder Style', "class": 'Blood Berserker', "tab": 0, "importance": 3, "bookable": True},
    201: {"name": 'Bulwark Style', "class": 'Blood Berserker', "tab": 0, "importance": 3, "bookable": True},
    202: {"name": "Famine O' Fish", "class": 'Blood Berserker', "tab": 0, "importance": 3, "bookable": True},
    203: {"name": 'Built Different', "class": 'Blood Berserker', "tab": 0, "importance": 3, "bookable": True},
    204: {"name": 'Ribbon Winning', "class": 'Blood Berserker', "tab": 0, "importance": 3, "bookable": True},
    205: {"name": 'Mass Irrigation', "class": 'Blood Berserker', "tab": 0, "importance": 3, "bookable": True},
    206: {"name": "Agricultural 'preciation", "class": 'Blood Berserker', "tab": 0, "importance": 3, "bookable": True},
    207: {"name": 'Dank Ranks', "class": 'Blood Berserker', "tab": 0, "importance": 3, "bookable": True},
    208: {"name": 'Wraith Overlord', "class": 'Blood Berserker', "tab": 0, "importance": 3, "bookable": True},
    209: {"name": 'Apocalypse Wow', "class": 'Blood Berserker', "tab": 0, "importance": 3, "bookable": True},
    263: {"name": 'Elusive Efficiency', "class": 'Archer', "tab": 0, "importance": 1, "bookable": True},
    265: {"name": 'Focused Soul', "class": 'Archer', "tab": 0, "importance": 3, "bookable": True},
    266: {"name": 'Featherweight', "class": 'Archer', "tab": 0, "importance": 3, "bookable": False},
    267: {"name": 'I See You', "class": 'Archer', "tab": 0, "importance": 3, "bookable": False},
    268: {"name": 'Idle Shooting', "class": 'Archer', "tab": 0, "importance": 1, "bookable": True},
    269: {"name": 'Broken Time', "class": 'Archer', "tab": 0, "importance": 1, "bookable": True},
    270: {"name": 'Piercing Arrow', "class": 'Archer', "tab": 0, "importance": 1, "bookable": True},
    271: {"name": 'Kung Fu Kick', "class": 'Archer', "tab": 0, "importance": 3, "bookable": True},
    272: {"name": 'Hema Overdrive', "class": 'Archer', "tab": 0, "importance": 2, "bookable": True},
    273: {"name": 'Strafe', "class": 'Archer', "tab": 0, "importance": 2, "bookable": True},
    274: {"name": 'Have Another!', "class": 'Archer', "tab": 0, "importance": 1, "bookable": True},
    276: {"name": "Garb Of Un'agi'ng Quality", "class": 'Archer', "tab": 0, "importance": 2, "bookable": True},
    277: {"name": 'High Polymer Limbs', "class": 'Archer', "tab": 0, "importance": 2, "bookable": True},
    278: {"name": 'Sanic Speed', "class": 'Archer', "tab": 0, "importance": 3, "bookable": True},
    279: {"name": 'Robbinghood', "class": 'Archer', "tab": 0, "importance": 2, "bookable": True},
    280: {"name": "Smeltin' Erryday", "class": 'Archer', "tab": 0, "importance": 3, "bookable": True},
    281: {"name": 'Acme Anvil', "class": 'Archer', "tab": 0, "importance": 3, "bookable": True},
    282: {"name": 'Yea I Already Know', "class": 'Archer', "tab": 0, "importance": 3, "bookable": True},
    283: {"name": 'Godly Creation', "class": 'Archer', "tab": 0, "importance": 3, "bookable": True},
    284: {"name": 'Veins Of The Infernal', "class": 'Archer', "tab": 0, "importance": 3, "bookable": True},
    285: {"name": 'Homing Arrows', "class": 'Archer', "tab": 0, "importance": 2, "bookable": True},
    286: {"name": 'Magic Shortbow', "class": 'Archer', "tab": 0, "importance": 2, "bookable": True},
    287: {"name": 'Flax Instastring', "class": 'Archer', "tab": 0, "importance": 3, "bookable": True},
    288: {"name": 'Extendo Rangeo', "class": 'Archer', "tab": 0, "importance": 3, "bookable": True},
    289: {"name": 'Woah, That Was Fast!', "class": 'Archer', "tab": 0, "importance": 3, "bookable": True},
    290: {"name": 'Speedna', "class": 'Archer', "tab": 0, "importance": 3, "bookable": True},
    291: {"name": 'Shoeful Of Obol', "class": 'Archer', "tab": 0, "importance": 3, "bookable": True},
    292: {"name": 'Shwifty Statues', "class": 'Archer', "tab": 0, "importance": 3, "bookable": True},
    293: {"name": 'Agi Again', "class": 'Archer', "tab": 0, "importance": 3, "bookable": True},
    294: {"name": 'Velocity Vessels', "class": 'Archer', "tab": 0, "importance": 3, "bookable": True},
    295: {"name": "Teleki'net'ic Logs", "class": 'Archer', "tab": 0, "importance": 3, "bookable": True},
    296: {"name": 'Briar Patch Runner', "class": 'Archer', "tab": 0, "importance": 3, "bookable": True},
    297: {"name": 'Bug Enthusiast', "class": 'Archer', "tab": 0, "importance": 3, "bookable": True},
    298: {"name": 'Sunset On The Hives', "class": 'Archer', "tab": 0, "importance": 3, "bookable": True},
    299: {"name": 'Previous Points', "class": 'Archer', "tab": 0, "importance": 3, "bookable": True},
    300: {"name": '360 Noscope', "class": 'Archer', "tab": 0, "importance": 3, "bookable": True},
    301: {"name": 'Bear Trap', "class": 'Archer', "tab": 0, "importance": 3, "bookable": True},
    302: {"name": 'Uwu Rawrrr', "class": 'Archer', "tab": 0, "importance": 3, "bookable": True},
    303: {"name": 'Stop Right There', "class": 'Archer', "tab": 0, "importance": 3, "bookable": True},
    304: {"name": 'Have Another... Again!', "class": 'Archer', "tab": 0, "importance": 3, "bookable": True},
    305: {"name": 'Looty Mc Shooty', "class": 'Archer', "tab": 0, "importance": 3, "bookable": True},
    307: {"name": 'Straightshot Statues', "class": 'Bowman', "tab": 0, "importance": 3, "bookable": True},
    309: {"name": 'Visibility Vessels', "class": 'Bowman', "tab": 0, "importance": 3, "bookable": True},
    310: {"name": 'Eagle Eye', "class": 'Bowman', "tab": 0, "importance": 3, "bookable": True},
    311: {"name": 'Invasive Species', "class": 'Bowman', "tab": 0, "importance": 3, "bookable": True},
    312: {"name": 'Shroom Bait', "class": 'Bowman', "tab": 0, "importance": 3, "bookable": True},
    313: {"name": 'Reflective Eyesight', "class": 'Bowman', "tab": 0, "importance": 3, "bookable": True},
    315: {"name": 'Ballista', "class": 'Bowman', "tab": 0, "importance": 3, "bookable": True},
    316: {"name": 'Suppressing Fire', "class": 'Bowman', "tab": 0, "importance": 3, "bookable": True},
    317: {"name": 'Firebomb', "class": 'Bowman', "tab": 0, "importance": 3, "bookable": True},
    318: {"name": 'Pirate Flag', "class": 'Bowman', "tab": 0, "importance": 3, "bookable": True},
    319: {"name": 'Plunder Ye Deceased', "class": 'Bowman', "tab": 0, "importance": 3, "bookable": True},
    320: {"name": 'Crew Rowing Strength', "class": 'Bowman', "tab": 0, "importance": 3, "bookable": True},
    325: {"name": 'Unending Loot Search', "class": 'Bowman', "tab": 0, "importance": 3, "bookable": True},
    326: {"name": 'Expertly Sailed', "class": 'Bowman', "tab": 0, "importance": 3, "bookable": True},
    327: {"name": 'Captain Peptalk', "class": 'Bowman', "tab": 0, "importance": 3, "bookable": True},
    328: {"name": 'Archlord Of The Pirates', "class": 'Bowman', "tab": 0, "importance": 3, "bookable": True},
    360: {"name": 'Cannonball', "class": 'Hunter', "tab": 0, "importance": 3, "bookable": True},
    361: {"name": 'Boar Rush', "class": 'Hunter', "tab": 0, "importance": 3, "bookable": True},
    362: {"name": 'Whale Wallop', "class": 'Hunter', "tab": 0, "importance": 3, "bookable": True},
    363: {"name": 'Nacho Party', "class": 'Hunter', "tab": 0, "importance": 3, "bookable": True},
    364: {"name": 'Have Yet Anotha One', "class": 'Hunter', "tab": 0, "importance": 3, "bookable": True},
    365: {"name": 'Animalistic Ferocity', "class": 'Hunter', "tab": 0, "importance": 3, "bookable": True},
    366: {"name": 'Stacked Skulls', "class": 'Hunter', "tab": 0, "importance": 3, "bookable": True},
    367: {"name": 'Skill Ambidexterity', "class": 'Hunter', "tab": 0, "importance": 3, "bookable": True},
    368: {"name": 'Adaptation Revelation', "class": 'Hunter', "tab": 0, "importance": 3, "bookable": True},
    370: {"name": 'Arena Spirit', "class": 'Hunter', "tab": 0, "importance": 3, "bookable": True},
    371: {"name": 'I Dream Of Peace And Egg', "class": 'Hunter', "tab": 0, "importance": 3, "bookable": True},
    372: {"name": 'Shining Beacon Of Egg', "class": 'Hunter', "tab": 0, "importance": 3, "bookable": True},
    373: {"name": 'Curviture Of The Paw', "class": 'Hunter', "tab": 0, "importance": 3, "bookable": True},
    374: {"name": 'Symbols Of Beyond ~g', "class": 'Hunter', "tab": 0, "importance": 3, "bookable": True},
    420: {"name": 'Tempest Form', "class": 'Siege Breaker', "tab": 0, "importance": 3, "bookable": True},
    421: {"name": 'Compass', "class": 'Siege Breaker', "tab": 0, "importance": 3, "bookable": True},
    422: {"name": 'Spirit Ballista', "class": 'Siege Breaker', "tab": 0, "importance": 3, "bookable": True},
    423: {"name": 'Eternal Hunt', "class": 'Siege Breaker', "tab": 0, "importance": 3, "bookable": True},
    424: {"name": 'Some Commandments', "class": 'Siege Breaker', "tab": 0, "importance": 3, "bookable": True},
    425: {"name": 'Windborne', "class": 'Siege Breaker', "tab": 0, "importance": 3, "bookable": True},
    426: {"name": 'Elemental Mayhem', "class": 'Siege Breaker', "tab": 0, "importance": 3, "bookable": True},
    427: {"name": "Pumpin' Power", "class": 'Siege Breaker', "tab": 0, "importance": 3, "bookable": True},
    428: {"name": 'Unreal Agility', "class": 'Siege Breaker', "tab": 0, "importance": 3, "bookable": True},
    429: {"name": 'Shiny Medallions', "class": 'Siege Breaker', "tab": 0, "importance": 3, "bookable": True},
    430: {"name": 'Price Recession', "class": 'Siege Breaker', "tab": 0, "importance": 3, "bookable": True},
    431: {"name": 'Sneaky Skilling', "class": 'Siege Breaker', "tab": 0, "importance": 3, "bookable": True},
    432: {"name": 'Generational Gemstones', "class": 'Siege Breaker', "tab": 0, "importance": 3, "bookable": True},
    433: {"name": 'Dustwalker', "class": 'Siege Breaker', "tab": 0, "importance": 3, "bookable": True},
    434: {"name": 'Slayer Abominator', "class": 'Siege Breaker', "tab": 0, "importance": 3, "bookable": True},
    445: {"name": 'Smart Efficiency', "class": 'Mage', "tab": 0, "importance": 1, "bookable": True},
    446: {"name": 'Overclocked Energy', "class": 'Mage', "tab": 0, "importance": 3, "bookable": False},
    447: {"name": 'Farsight', "class": 'Mage', "tab": 0, "importance": 3, "bookable": False},
    448: {"name": 'Idle Casting', "class": 'Mage', "tab": 0, "importance": 1, "bookable": True},
    449: {"name": "Active Afk'er", "class": 'Mage', "tab": 0, "importance": 1, "bookable": True},
    450: {"name": 'Energy Bolt', "class": 'Mage', "tab": 0, "importance": 1, "bookable": True},
    451: {"name": 'Mini Fireball', "class": 'Mage', "tab": 0, "importance": 3, "bookable": True},
    452: {"name": 'Mana Overdrive', "class": 'Mage', "tab": 0, "importance": 4, "bookable": True},
    453: {"name": 'Teleport', "class": 'Mage', "tab": 0, "importance": 3, "bookable": True},
    454: {"name": "You're Next", "class": 'Mage', "tab": 0, "importance": 1, "bookable": True},
    455: {"name": 'Knowledge Is Power', "class": 'Mage', "tab": 0, "importance": 1, "bookable": True},
    456: {"name": "Unt'wis'ted Robes", "class": 'Mage', "tab": 0, "importance": 2, "bookable": True},
    457: {"name": 'Power Overwhelming', "class": 'Mage', "tab": 0, "importance": 1, "bookable": True},
    458: {"name": 'Free Meal', "class": 'Mage', "tab": 0, "importance": 1, "bookable": True},
    459: {"name": 'Individual Insight', "class": 'Mage', "tab": 0, "importance": 1, "bookable": True},
    460: {"name": 'Log On Logs', "class": 'Mage', "tab": 0, "importance": 3, "bookable": True},
    461: {"name": 'Leaf Thief', "class": 'Mage', "tab": 0, "importance": 3, "bookable": True},
    462: {"name": 'Deforesting All Doubt', "class": 'Mage', "tab": 0, "importance": 3, "bookable": True},
    463: {"name": 'Choppin It Up Ez', "class": 'Mage', "tab": 0, "importance": 3, "bookable": True},
    464: {"name": 'Inner Peace', "class": 'Mage', "tab": 0, "importance": 3, "bookable": True},
    465: {"name": 'Ice Shards', "class": 'Mage', "tab": 0, "importance": 3, "bookable": True},
    466: {"name": 'Floor Is Lava', "class": 'Mage', "tab": 0, "importance": 3, "bookable": True},
    467: {"name": 'Tornado', "class": 'Mage', "tab": 0, "importance": 3, "bookable": True},
    468: {"name": 'Speedy Book', "class": 'Mage', "tab": 0, "importance": 3, "bookable": True},
    469: {"name": 'Mana Is Life', "class": 'Mage', "tab": 0, "importance": 4, "bookable": True},
    470: {"name": 'Paperwork, Great...', "class": 'Mage', "tab": 0, "importance": 3, "bookable": True},
    472: {"name": 'Staring Statues', "class": 'Mage', "tab": 0, "importance": 3, "bookable": True},
    474: {"name": 'Fuscia Flasks', "class": 'Mage', "tab": 0, "importance": 3, "bookable": True},
    475: {"name": 'Charge Syphon', "class": 'Mage', "tab": 0, "importance": 3, "bookable": True},
    476: {"name": 'Sooouls', "class": 'Mage', "tab": 0, "importance": 3, "bookable": True},
    477: {"name": 'Bless Up', "class": 'Mage', "tab": 0, "importance": 3, "bookable": True},
    478: {"name": 'Nearby Outlet', "class": 'Mage', "tab": 0, "importance": 3, "bookable": True},
    480: {"name": 'Crazy Concoctions', "class": 'Mage', "tab": 0, "importance": 3, "bookable": True},
    481: {"name": 'Auspicious Aura', "class": 'Mage', "tab": 0, "importance": 3, "bookable": True},
    482: {"name": 'Sizzling Skull', "class": 'Mage', "tab": 0, "importance": 3, "bookable": True},
    483: {"name": 'Tenteyecle', "class": 'Mage', "tab": 0, "importance": 3, "bookable": True},
    484: {"name": 'Instant Invincibility', "class": 'Mage', "tab": 0, "importance": 3, "bookable": True},
    485: {"name": 'Virile Vials', "class": 'Mage', "tab": 0, "importance": 3, "bookable": True},
    486: {"name": 'Occult Obols', "class": 'Mage', "tab": 0, "importance": 3, "bookable": True},
    487: {"name": 'Stupendous Statues', "class": 'Mage', "tab": 0, "importance": 3, "bookable": True},
    488: {"name": 'Wis Wumbo', "class": 'Mage', "tab": 0, "importance": 3, "bookable": True},
    489: {"name": 'Fantasia Flasks', "class": 'Mage', "tab": 0, "importance": 3, "bookable": True},
    490: {"name": 'Cranium Cooking', "class": 'Mage', "tab": 0, "importance": 3, "bookable": True},
    491: {"name": "Busy Brewin'", "class": 'Mage', "tab": 0, "importance": 3, "bookable": True},
    492: {"name": 'Bubble Breakthrough', "class": 'Mage', "tab": 0, "importance": 3, "bookable": True},
    493: {"name": 'Sharing Some Smarts', "class": 'Mage', "tab": 0, "importance": 3, "bookable": True},
    494: {"name": 'Earlier Education', "class": 'Mage', "tab": 0, "importance": 3, "bookable": True},
    495: {"name": 'Meteor Shower', "class": 'Mage', "tab": 0, "importance": 3, "bookable": True},
    496: {"name": 'Lightning Barrage', "class": 'Mage', "tab": 0, "importance": 3, "bookable": True},
    497: {"name": 'Radiant Chainbolt', "class": 'Mage', "tab": 0, "importance": 3, "bookable": True},
    498: {"name": 'Dimensional Wormhole', "class": 'Mage', "tab": 0, "importance": 3, "bookable": True},
    499: {"name": 'Chaotic Force', "class": 'Mage', "tab": 0, "importance": 3, "bookable": True},
    500: {"name": 'Believer Strength', "class": 'Wizard', "tab": 0, "importance": 3, "bookable": True},
    505: {"name": 'Polytheism', "class": 'Wizard', "tab": 0, "importance": 3, "bookable": True},
    506: {"name": 'Shared Beliefs', "class": 'Wizard', "tab": 0, "importance": 3, "bookable": True},
    507: {"name": 'Gods Chosen Children', "class": 'Wizard', "tab": 0, "importance": 3, "bookable": True},
    508: {"name": 'Wormhole Emperor', "class": 'Wizard', "tab": 0, "importance": 3, "bookable": True},
    525: {"name": 'Chemical Warfare', "class": 'Shaman', "tab": 0, "importance": 3, "bookable": True},
    526: {"name": 'Flatulent Spirit', "class": 'Shaman', "tab": 0, "importance": 3, "bookable": True},
    527: {"name": 'Tampered Injection', "class": 'Shaman', "tab": 0, "importance": 3, "bookable": True},
    528: {"name": 'Plague Stricken', "class": 'Shaman', "tab": 0, "importance": 3, "bookable": True},
    529: {"name": 'Raise Dead', "class": 'Shaman', "tab": 0, "importance": 3, "bookable": True},
    530: {"name": 'Wired In Power', "class": 'Shaman', "tab": 0, "importance": 3, "bookable": True},
    531: {"name": 'Memorial Skulls', "class": 'Shaman', "tab": 0, "importance": 3, "bookable": True},
    532: {"name": 'Skill Wiz', "class": 'Shaman', "tab": 0, "importance": 3, "bookable": True},
    533: {"name": 'Utmost Intellect', "class": 'Shaman', "tab": 0, "importance": 3, "bookable": True},
    535: {"name": 'Purple Tube', "class": 'Shaman', "tab": 0, "importance": 3, "bookable": True},
    536: {"name": 'Green Tube', "class": 'Shaman', "tab": 0, "importance": 3, "bookable": True},
    537: {"name": 'Essence Transferral', "class": 'Shaman', "tab": 0, "importance": 3, "bookable": True},
    538: {"name": 'Upload Squared', "class": 'Shaman', "tab": 0, "importance": 3, "bookable": True},
    539: {"name": 'Symbols Of Beyond ~p', "class": 'Shaman', "tab": 0, "importance": 3, "bookable": True},
    585: {"name": 'Arcanist Form', "class": 'Elemental Sorcerer', "tab": 0, "importance": 3, "bookable": True},
    586: {"name": 'Tesseract', "class": 'Elemental Sorcerer', "tab": 0, "importance": 3, "bookable": True},
    587: {"name": 'Arcane Skulls', "class": 'Elemental Sorcerer', "tab": 0, "importance": 3, "bookable": True},
    588: {"name": 'Arcane Crystals', "class": 'Elemental Sorcerer', "tab": 0, "importance": 3, "bookable": True},
    589: {"name": 'Overwhelming Energy', "class": 'Elemental Sorcerer', "tab": 0, "importance": 3, "bookable": True},
    590: {"name": 'Ghastly Power', "class": 'Elemental Sorcerer', "tab": 0, "importance": 3, "bookable": True},
    591: {"name": 'Ghoulish Power', "class": 'Elemental Sorcerer', "tab": 0, "importance": 3, "bookable": True},
    592: {"name": 'Labotomizer', "class": 'Elemental Sorcerer', "tab": 0, "importance": 3, "bookable": True},
    593: {"name": 'Individuality', "class": 'Elemental Sorcerer', "tab": 0, "importance": 3, "bookable": True},
    594: {"name": 'Primo Prisma', "class": 'Elemental Sorcerer', "tab": 0, "importance": 3, "bookable": True},
    595: {"name": 'Essential Essence', "class": 'Elemental Sorcerer', "tab": 0, "importance": 3, "bookable": True},
    596: {"name": 'Passion Of The Summon', "class": 'Elemental Sorcerer', "tab": 0, "importance": 3, "bookable": True},
    597: {"name": 'Absolute Stardom', "class": 'Elemental Sorcerer', "tab": 0, "importance": 3, "bookable": True},
    598: {"name": 'Tachyon Truth', "class": 'Elemental Sorcerer', "tab": 0, "importance": 3, "bookable": True},
    599: {"name": 'Backup Energy', "class": 'Elemental Sorcerer', "tab": 0, "importance": 3, "bookable": True},
}
